### ISSUE TITLE
Consider releasing as an independent extension

### ISSUE THREAD

**Issue by jacksongoode** [SUPERCILEX/gnome-clipboard-history#1]
With the breadth of your changes and the (often slow) speed at which Tudmotu responses to PR's, I imagine you will have more traction (and thanks) from folks who find this extension essential and want something much more optimized and maintained. What do you think?

**Comment by SUPERCILEX** [comment]
This is what's going to end up happening! Tudmotu and I have been going back and forth and he decided to keep the original clipboard indicator as is so he can guarantee stability. From him:

> Wish you good luck and hopefully your extensions will become more popular than mine and I can finally stop maintaining this one lol

That's going to be the goal! I think we'll get there. :)

**Comment by SUPERCILEX** [comment]
It is done! https://extensions.gnome.org/extension/4839/clipboard-history/

Still need to finalize a few things before I start making announcements and I'm also planning to write a blog post on how the internals work.

**Comment by jacksongoode** [comment]
Fantastic! I will be following your progress closely! I'll open a few issues/features I've held back from the original extension as well :)
