### ISSUE TITLE
"save selected text" updates too frequently

### ISSUE THREAD

**Issue by SwissalpS** [SUPERCILEX/gnome-clipboard-history#100]
### Problem description
when the "save selected text" option is on, the history is filled with many entries while selecting text.

### Potential solutions/workarounds
a) poll less frequently
or b) compare new selection with last entry and if the beginning or end match, replace previous entry with current one.

### Additional context
For the time being, could somebody point me to where in code I could set the poll interval to a longer period?

**Comment by SwissalpS** [comment]
probably also needs a check if there is a last entry at all.

**Comment by SUPERCILEX** [comment]
Quick thoughts: your solution seems reasonable to enable when selected text is enabled. I hate the timeout thing anyway so it'd be great to get rid of it.

**Comment by SUPERCILEX** [comment]
Quick thoughts: your solution seems reasonable to enable when selected text is enabled. I hate the timeout thing anyway so it'd be great to get rid of it.

**Comment by SwissalpS** [comment]
there's just the side effect to be considered:
if somebody wants to have "somebod@somewhere.tld" but also "somebod" and "somewhere.tld" in three separate slots, he best start with the full one as starting with either of the others would overwrite them.

**Comment by SUPERCILEX** [comment]
Eh, not really worth it. Your solution only overwrites longer strings so that means users have a superset of the information. You haven't lost anything and can just delete the part you don't want.

**Comment by SwissalpS** [comment]
I'm wondering if a minimum length limit would make sense.
I'm getting a lot of single chars from correcting e.g. a -> á

For my current use, I wouldn't mind having to ctrl-c for single or double chars maybe even three.
But this filter is probably not worth the hastle. UX is smoother without it.
(The hastle comming from adding to config etc.)

**Comment by SwissalpS** [comment]
thanks :D

**Comment by SwissalpS** [comment]
It has been working quite well.
Though, if one selects too much and then de-selects again, one can still fill the log with
entries like this:
```
i have no issue w/ arguing m
....
i have no issue w/ arguing my positio
i have no issue w/ arguing my position.
```
I guess we just need to be aware of it and start selecting freshly instead of reducing selection.
I'm not sure if dropping the length check and only checking for starts with and ends with both ways would help.

**Comment by SUPERCILEX** [comment]
Ok, I actually like the new direction a lot: it now acts as a perfect mirror to whatever you've selected which seems much more intuitive.

**Comment by SUPERCILEX** [comment]
Also a note for future people: the length is needed so re-selecting something (by double clicking a word for example) doesn't delete it.

**Comment by SwissalpS** [comment]
are you sure, about the doublclick?
I did this patch and am delighted. Double click works fine for me.
```diff
@@ -830,8 +830,9 @@ class ClipboardIndicator extends PanelMenu.Button {
       if (
         last &&
         text &&
-        text.length > last.text.length &&
-        (text.endsWith(last.text) || text.startsWith(last.text))
+        //text.length > last.text.length &&
+        ((text.endsWith(last.text) || text.startsWith(last.text) ||
+        last.text.endsWith(text) || last.text.startsWith(text)))
       ) {
         this._removeEntry(last, true);
       }
@@ -1283,3 +1284,4 @@ function disable() {
```

**Comment by SwissalpS** [comment]
oops, you've already updated some more.

OK, I see what you mean with the length check, yeah that's good.
