### ISSUE TITLE
copy&paste broken in vscode

### ISSUE THREAD

**Issue by str** [SUPERCILEX/gnome-clipboard-history#103]
### Describe the bug

After latest update, everytime I copy something from vscode, it's not coppied to the clipboard.  It does not happen with other apps.

### How To Reproduce

install vscode via apt
open it
copy some text
paste it, nothing is pasted

#### Versions

- vscode 1.17.2
Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:12:14.256Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-48-generic
Sandboxed: No

GNOME Shell 42.4
GCH   Version: 20
org.gnome.shell.extensions.clipboard-history cache-only-favorites false
org.gnome.shell.extensions.clipboard-history cache-size 100
org.gnome.shell.extensions.clipboard-history clear-history @as []
org.gnome.shell.extensions.clipboard-history confirm-clear true
org.gnome.shell.extensions.clipboard-history disable-down-arrow true
org.gnome.shell.extensions.clipboard-history display-mode 0
org.gnome.shell.extensions.clipboard-history enable-keybindings true
org.gnome.shell.extensions.clipboard-history history-size 1000
org.gnome.shell.extensions.clipboard-history move-item-first true
org.gnome.shell.extensions.clipboard-history next-entry @as []
org.gnome.shell.extensions.clipboard-history notify-on-copy false
org.gnome.shell.extensions.clipboard-history paste-on-selection true
org.gnome.shell.extensions.clipboard-history prev-entry @as []
org.gnome.shell.extensions.clipboard-history private-mode false
org.gnome.shell.extensions.clipboard-history process-primary-selection true
org.gnome.shell.extensions.clipboard-history strip-text true
org.gnome.shell.extensions.clipboard-history toggle-menu ['<Super><Shift>V']
org.gnome.shell.extensions.clipboard-history toggle-private-mode ['<Super><Shift>P']
org.gnome.shell.extensions.clipboard-history topbar-preview-size 1
org.gnome.shell.extensions.clipboard-history window-width-percentage 20

#### Steps to repro

What causes the crash/bug? I don't know

**Comment by SUPERCILEX** [comment]
Need to investigate further, but this almost certainly caused by the Save selected text setting. Turn that off for now.

**Comment by str** [comment]
Confirmed, that solved the issue temporarily.
