### ISSUE TITLE
No clipboard history is shown

### ISSUE THREAD

**Issue by drabb** [SUPERCILEX/gnome-clipboard-history#107]
### Describe the bug

No clipboard history is shown in the UI panel.

#### Versions

```sh
GNOME Shell 42.5
GCH   Version: 21
org.gnome.shell.extensions.clipboard-history cache-only-favorites false
org.gnome.shell.extensions.clipboard-history cache-size 100
org.gnome.shell.extensions.clipboard-history clear-history @as []
org.gnome.shell.extensions.clipboard-history confirm-clear true
org.gnome.shell.extensions.clipboard-history disable-down-arrow true
org.gnome.shell.extensions.clipboard-history display-mode 0
org.gnome.shell.extensions.clipboard-history enable-keybindings true
org.gnome.shell.extensions.clipboard-history history-size 1000
org.gnome.shell.extensions.clipboard-history move-item-first true
org.gnome.shell.extensions.clipboard-history next-entry @as []
org.gnome.shell.extensions.clipboard-history notify-on-copy false
org.gnome.shell.extensions.clipboard-history paste-on-selection true
org.gnome.shell.extensions.clipboard-history prev-entry @as []
org.gnome.shell.extensions.clipboard-history private-mode false
org.gnome.shell.extensions.clipboard-history process-primary-selection false
org.gnome.shell.extensions.clipboard-history strip-text true
org.gnome.shell.extensions.clipboard-history toggle-menu ['<Super><Shift>V']
org.gnome.shell.extensions.clipboard-history toggle-private-mode ['<Super><Shift>P']
org.gnome.shell.extensions.clipboard-history topbar-preview-size 10
org.gnome.shell.extensions.clipboard-history window-width-percentage 25
```

#### Steps to repro

No specific user action - just open the panel from the notification bar, or using the global keyboard shortcut after copying any text/image.

### Additional context (if a crash, provide stack trace)

Leaving `gnome-shell` logs below

```sh
drabb@x13 ~/Desktop $ journalctl /usr/bin/gnome-shell -f -o cat
...
JS ERROR: TypeError: undefined has no properties
loop/<@/home/drabb/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/store.js:144:56
parseAvailableAware@/home/drabb/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/store.js:189:7
loop@/home/drabb/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/store.js:142:26
loop/<@/home/drabb/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/store.js:137:11
...
```

![image](https://user-images.githubusercontent.com/764109/194646308-17062582-429e-4ede-911f-2158a46b7278.png)

**Comment by SUPERCILEX** [comment]
This is some kind of corruption issue. To fix it, you can run `mv ~/.cache/clipboard-history@alexsaveau.dev/database.log ~/.cache/clipboard-history@alexsaveau.dev/corrupted.log` and then log out and log back in (or restart gnome shell, or reboot).

If you're comfortable, would you mind sharing the database with me? Or maybe just running metadata analysis on it? Let me know if you're comfortable with either and I'll give you further instructions.

**Comment by drabb** [comment]
Backing up the log file and a logout did the trick.

Sorry can't share the database. This happened on my work computer, so no telling what was on my clipboard. Not sure what is meant by metadata analysis but maybe.

Thanks for the quick reply and for making a great extension.

**Comment by SUPERCILEX** [comment]
If you can share the metadata, that would be helpful:
1. Install Rust if you don't already have it: https://doc.rust-lang.org/cargo/getting-started/installation.html
2. `$ git clone https://github.com/SUPERCILEX/gnome-clipboard-history.git`
3. `$ cd gnome-clipboard-history/tools`
4. `$ cargo r -- d ~/.cache/clipboard-history@alexsaveau.dev/corrupted.log > metadata.txt`

This will dump the database metadata as a list of inserts, deletes, moves, and favorites. No clipboard content will be present. I'm basically looking to try and understand how the database was corrupted. My current guess is that there will be duplicate inserts and deletes.

**Comment by drabb** [comment]
[metadata.txt](https://github.com/SUPERCILEX/gnome-clipboard-history/files/9745901/metadata.txt)

Think attachment here should work - otherwise I'll upload as a gist.
