### ISSUE TITLE
Timer for cleaning clipboard history

### ISSUE THREAD

**Issue by muznyo** [SUPERCILEX/gnome-clipboard-history#108]
Add option to clear clipboard history automatically after specific time period set in extension settings.

**Comment by SUPERCILEX** [comment]
Thanks for the suggestion, but this isn't going to happen. You can already:
- Delete non-favorited items on reboot by choosing the "Only save favorites to disk" option.
- Delete items after they exceed a count or storage size though the "Max number of items" and "Max clipboard history size" options.

If #40 ends up happening, then perhaps this would make sense, but I currently don't the the value justifying the complexity.
