### ISSUE TITLE
Favorites gone

### ISSUE THREAD

**Issue by BIRO-IS** [SUPERCILEX/gnome-clipboard-history#113]
Hi, after the last extension update there was a notification, that my favourites were saved somewhere. Unfortunately, I missed it, and now I am looking for my old favourites. Are they stored somewhere? Thanks in advance!

**Comment by SUPERCILEX** [comment]
Do you mean a corruption issue? There would be a file in `~/.cache/clipboard-history@alexsaveau.dev/`.

**Comment by BIRO-IS** [comment]
Exactly what I was looking for. Thank you so much! :)
