### ISSUE TITLE
Please make an option to copy cut text and copy text

### ISSUE THREAD

**Issue by shahil-leo** [SUPERCILEX/gnome-clipboard-history#114]
Please make an option to copy only the one i wish to copy not the ctrl+x i dont need the cut ones in my clipboard history so if you can please add and option to copy only ctrl+c not the ctrl+x give an option in the settings of the extension then it will be usefull for me its a request

**Comment by SUPERCILEX** [comment]
There's no way to tell how the text was copied AFAIK, so this won't be possible.
