### ISSUE TITLE
Show pin button when mouse over list item

### ISSUE THREAD

**Issue by iman-salmani** [SUPERCILEX/gnome-clipboard-history#115]
### Problem description
hi
it's hard to know about invisible button

### Potential solutions/workarounds
show pin button when user hover list item

### Additional context
thanks for your extension
I use this extension for store my test values

**Comment by SUPERCILEX** [comment]
You're probably using a broken theme since we don't touch the icon colors. Here's what it should look like:
![image](https://user-images.githubusercontent.com/9490724/207168331-45d96e18-a62a-4e7f-9bf1-884811f09cdd.png)

**Comment by iman-salmani** [comment]
i tested this on arch and fedora with gnome 43 default theme
![gnome-clipboard-pin](https://user-images.githubusercontent.com/32843050/208247563-396803f1-f92e-4c76-a50b-443bf3fbc4d4.png)
