### ISSUE TITLE
Your clipboard data has been corrupted and was moved to:

### ISSUE THREAD

**Issue by SwissalpS** [SUPERCILEX/gnome-clipboard-history#122]
### Describe the bug

I looked at the top bar and my clipboard history was gone, instead it had only one entry:
"Your clipboard data has been corrupted and was moved to:" 
A day later I wake my computer up and again that message, but this time there are some more items: 
- a path to where the clipboard has been moved
- Please file a bug report at:
- https://github.com/SUPERCILEX/gnome-clipboard-history/issues/new?assignees=&labels=bug&template=1-bug.md

### How To Reproduce
no idea, have used it normally. maybe having PC sleep has influence
#### Versions

GNOME Shell 43.3
GCH org.gnome.shell.extensions.clipboard-history cache-only-favorites false
org.gnome.shell.extensions.clipboard-history cache-size 100
org.gnome.shell.extensions.clipboard-history clear-history @as []
org.gnome.shell.extensions.clipboard-history confirm-clear true
org.gnome.shell.extensions.clipboard-history disable-down-arrow true
org.gnome.shell.extensions.clipboard-history display-mode 2
org.gnome.shell.extensions.clipboard-history enable-keybindings false
org.gnome.shell.extensions.clipboard-history history-size 1000
org.gnome.shell.extensions.clipboard-history move-item-first true
org.gnome.shell.extensions.clipboard-history next-entry @as []
org.gnome.shell.extensions.clipboard-history notify-on-copy false
org.gnome.shell.extensions.clipboard-history paste-on-selection false
org.gnome.shell.extensions.clipboard-history prev-entry @as []
org.gnome.shell.extensions.clipboard-history private-mode false
org.gnome.shell.extensions.clipboard-history process-primary-selection false
org.gnome.shell.extensions.clipboard-history strip-text false
org.gnome.shell.extensions.clipboard-history toggle-menu ['<Super><Shift>V']
org.gnome.shell.extensions.clipboard-history toggle-private-mode ['<Super><Shift>P']

#### Steps to repro

What causes the crash/bug?

### Additional context (if a crash, provide stack trace)

I also see now that there is an update, maybe this has already been fixed?

**Comment by SwissalpS** [comment]
[database.log](https://github.com/SUPERCILEX/gnome-clipboard-history/files/10880459/database.log)
[corrupted.log](https://github.com/SUPERCILEX/gnome-clipboard-history/files/10880460/corrupted.log)

**Comment by SUPERCILEX** [comment]
@SwissalpS looks like your database is still broken. You'll want to run this command in the terminal `gio trash ~/.cache/clipboard-history@alexsaveau.dev/database.log` and then restart.

---

Well, I still have no idea what's going on. Saving this for posterity:

```
$ cargo r d ~/Desktop/corrupted.log
SAVE_TEXT@1
Id: 1

MOVE_ITEM_TO_END@59
Id: 523

SAVE_TEXT@64
Length: 35
Id: 2

SAVE_TEXT@100
Length: 50
Id: 3

SAVE_TEXT@151
Length: 50
Id: 4

$ cargo r d ~/Desktop/database.log
MOVE_ITEM_TO_END@1
Id: 556

SAVE_TEXT@6
Length: 105
Id: 1

MOVE_ITEM_TO_END@112
Id: 556

SAVE_TEXT@117
Length: 29
Id: 2

MOVE_ITEM_TO_END@147
Id: 560

MOVE_ITEM_TO_END@152
Id: 561

MOVE_ITEM_TO_END@157
Id: 556

SAVE_TEXT@162
Length: 56
Id: 3
```

**Comment by letavocado** [comment]
Hey @SUPERCILEX! 

I am facing the same issue.

Cheers!
