### ISSUE TITLE
Please Remove from Gnome Extensions

### ISSUE THREAD

**Issue by kale1d0code** [SUPERCILEX/gnome-clipboard-history#129]
### Describe the bug

Uninstalled Extension. Extension keeps reinstalling and severely crashing the Gnome Desktop Manager. requires disabling all extensions and restarting computer to get control back.

#### Versions

PASTE_OUTPUT_HERE

#### Steps to repro

What causes the crash/bug?
This plugin

**Comment by SUPERCILEX** [comment]
That's not something a gnome extension can do, so something else it at fault.
