### ISSUE TITLE
Github releases

### ISSUE THREAD

**Issue by jonian** [SUPERCILEX/gnome-clipboard-history#131]
Hi @SUPERCILEX, thank you for this extension. This is not a bug report .

I'm maintaining an AUR package for this and it would be very helpful if you used the github releases so I, and other package maintainers, can get notifications when a new version is released. 

Thanks!

**Comment by SUPERCILEX** [comment]
Pretty sure I do: https://github.com/SUPERCILEX/gnome-clipboard-history/releases/tag/1.3.2

**Comment by jonian** [comment]
Maybe the you just forgot the latest release. Your latest tag is 1.3.3. Thanks for the quick response!

**Comment by SUPERCILEX** [comment]
Oh, my bad lol. Just forgot, fixed.
