### ISSUE TITLE
Update Panel Indicator style from 'system-status-icon' to 'popup-menu-icon'

### ISSUE THREAD

**Issue by hedgieinsocks** [SUPERCILEX/gnome-clipboard-history#132]
https://github.com/SUPERCILEX/gnome-clipboard-history/blob/fdbd4bfb3e6bacb783304b4b36f4ad344c67a9af/extension.js#L74

Please consider switching from system-status-icon to popup-menu-icon style in the aforementioned code. This way, your extension's indicator will not have extra padding (like the language indicator has) and will not stand out from other concise indicators. 

Obviously, I'm opinionated but perhaps you can agree that we should strive for consistency and a uniform look of status area.

**Comment by SUPERCILEX** [comment]
popup-menu-icon:
![image](https://user-images.githubusercontent.com/9490724/235223686-156aa2e5-8c11-44e8-9b83-18c2277d9441.png)

system-status-icon:
![image](https://user-images.githubusercontent.com/9490724/235223779-395ee5ff-dfdc-400f-b303-8a4698cc6028.png)

Isn't it supposed to be a system status icon?

**Comment by hedgieinsocks** [comment]
Well, it looks like all the extensions and apps that create indicators in my setup use popup-menu-icon, and only clipboard history uses system-status-icon which makes it a bit of a white raven. But I now understand that it might be that someone's setup has it the other way, e.g. like yours. Which way is the way is not for me to decide. So it was just a suggestion. Maybe people start voting for this. For now, I ended up pinning clipboard history to the language icon (via https://extensions.gnome.org/extension/4356/top-bar-organizer/) so the extra spacing does not catch my eye and I can enjoy your app. Anyway, thank you for looking into it!

**Comment by SUPERCILEX** [comment]
BTW, if you always use a shortcut to open the clipboard, you can go in settings and disable the icon entirely (what I do). I'm going to close this because I'd rather do what feels "more correct" since this is a system status icon.
