### ISSUE TITLE
Show pictures in clipboard history

### ISSUE THREAD

**Issue by KolbyML** [SUPERCILEX/gnome-clipboard-history#133]
### Problem description
On windows clipboard history also stores pictures which is very useful and cool

**Comment by SUPERCILEX** [comment]
Yup, I'd love this as well: https://github.com/SUPERCILEX/gnome-clipboard-history/issues/6

Unfortunately, gnome extensions are just plain awful for writing low-level code, so this is probably never going to happen. The folks at PopOS are planning on [adding a clipboard to the Cosmic DE](https://blog.system76.com/post/may-flowers-spring-cosmic-showers#:~:text=In%20the%20future%2C%20applets%20can%20be%20added%20for%20a%20clipboard%2C%20notes%2C%20weather%2C%20custom%20menus%20or%20whatever%20feature%20you%20might%20imagine.) and while I'm still pissed at them for [some of their choices](https://github.com/pop-os/cosmic/pull/70), they've been doing great work and I believe the clipboard they implement will be done right. So basically I'm just waiting for Cosmic DE and probably going to let this extension slow die unless someone else can take it over.

**Comment by KolbyML** [comment]
@SUPERCILEX Cosmic DE is written in Rust and isn't GNOME. GNOME isn't going anywhere! PopOS might stop using it, but Ubuntu has a larger install base which means a extension like this still has a place. I have tried gpaste and it doesn't feel clean as this extension.

I wonder if someone will maintain this then after you

**Comment by SUPERCILEX** [comment]
> I wonder if someone will maintain this then after you

Yeah, to be clear I'm not going to completely forget about the extension. If someone sends in a PR, I'll take a look. I just won't fix breakage caused by gnome updates so the community will have to step up when that happens.
