### ISSUE TITLE
Disable notifications in Message Tray for system's "Do not Disturb" mode and extensions "Private" mode

### ISSUE THREAD

**Issue by xalt7x** [SUPERCILEX/gnome-clipboard-history#134]
### Problem description
I like switching clipboard items with "Previous..." and "Next entry" hotkeys.
Notifications during switch help to identify entries. They stay on a Message Tray for some time, then disappear.
In "Do not disturb" mode during switch user can't see notification of a current entry. And that's probably a reason why the record on a Message Tray never disappear.
Situation gets even more confusing with extensions which bring notification alerts and counters (e.g. "[Notification Counter](https://github.com/vkrizan/NotificationCounter)", "[Always Indicator](https://github.com/mzur/gnome-shell-always-indicator)" , "[Notification Alert](https://github.com/bellini666/gnome-shell-notifications-alert)", "[Rocketbar](https://github.com/linux-is-awesome/gnome_extension_rocketbar)"). User often gets increased number, indicator or alert which doesn't help to track important notifications.

### Potential solutions/workarounds
Disable notifications in "Do not disturb" mode.
I guess it would be nice to disable them for the "Private mode" as well.

### Additional context
I've seen that GNOME currently has [transient notifications](https://wiki.gnome.org/Design/OS/Notifications#Transient)
`notify-send --transient "Hello"`
but they behave similarly (never disappear in "Do not disturb" mode)

**Comment by SUPERCILEX** [comment]
I'd welcome a PR for both your solutions.
