### ISSUE TITLE
Unable to set desired keyboard shortcut

### ISSUE THREAD

**Issue by prajwel** [SUPERCILEX/gnome-clipboard-history#137]
### Describe the bug

I cannot set the previous entry shortcut to "Ctrl + Shift + F12". Whenever I try, it only shows "F12" as the shortcut. However, I am able to set other combinations, such as "Shift + Super + F12".

**Comment by SUPERCILEX** [comment]
My guess is that this shortcut is already bound to something at the system level? If it ends up being a bug with the extension, please do send over a PR.
