### ISSUE TITLE
Port to ESM (gnome 45 support)

### ISSUE THREAD

**Issue by bbhtt** [SUPERCILEX/gnome-clipboard-history#145]
### Problem description

GNOME Shell switched to ESM as part of 45 https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1499. This means all extensions will be broken unless ported.

See the GUADEC talk: https://youtu.be/qaZuQO0bK-M?t=21013

The official ones have already been ported https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/commit/a9114473751fd022a5208618a8c9bb488651a48a

### Additional context

The port, is not yet fully done. Docs will be out once it is done. (afaik)

**Comment by SUPERCILEX** [comment]
Does that break back compat? If so I think I'll want a separate branch.

Either way, I won't be able to do the migration because I'm in pop os land, but I'll happily accept a PR.

**Comment by bbhtt** [comment]
> Does that break back compat? If so I think I'll want a separate branch.

Asked in #extensions:gnome.org, was pointed to https://gjs.guide/extensions/upgrading/gnome-shell-45.html#shell-version, so yes in a way.

You'll have to upload multiple versions (if it is ported) to target older GNOME versions.

**Comment by darkdragon-001** [comment]
Usually you keep the old extension versions for old GNOME versions and continue development only for new versions.
