### ISSUE TITLE
Paste on selet

### ISSUE THREAD

**Issue by ricardosierra** [SUPERCILEX/gnome-clipboard-history#148]
### Problem description

As happens in Windows, I wanted to press windows+and open the window so I could select and paste directly. or at least. when I select paste direct

**Comment by SUPERCILEX** [comment]
This is an issue with gnome APIs being terrible. Technically this is how the extension works (try it in the terminal for example), but then it just doesn't work in some apps like chrome. Nothing I can really do unfortunately.
