### ISSUE TITLE
Add image clipboard history

### ISSUE THREAD

**Issue by ivan-toriya** [SUPERCILEX/gnome-clipboard-history#151]
**Problem Description**
Currently, the Gnome Clipboard History extension efficiently tracks and stores text that users have copied, allowing for easy access and searchability. However, an important aspect of clipboard functionality is missing - the ability to copy and store images. Users often copy images to the clipboard sp the absence of this feature limits the utility of the extension for a comprehensive clipboard experience.

**Potential Solutions/Workarounds**
Image Support Implementation: Enhance the extension to support image data types. This could involve creating a system where images are stored in a local cache, with thumbnails or file names displayed in the history panel.

**Additional Context**
The proposed feature is a logical extension of the current capabilities of the Gnome Clipboard History. It aligns with the goal of the extension, which is to provide a robust and comprehensive clipboard history experience. The original extension, [Clipboard Indicator,](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator) already has this feature, and its addition in the rewritten version would significantly enhance its utility.
![image](https://github.com/SUPERCILEX/gnome-clipboard-history/assets/43750521/b7fe8340-7298-428c-a582-d79f4d7c7786)

Forked from [this issue](https://github.com/SUPERCILEX/gnome-clipboard-history/issues/136) to specifically track image implementation.

**Comment by SUPERCILEX** [comment]
If someone would like to propose a design and send a PR, I'll happily work with them to get this implemented. Don't have time to do it myself unfortunately.

**Comment by Edu4rdSHL** [comment]
I would prefer to keep this as simple as it's. And, in the eventual implementation of this feature, please make sure that things like https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/453 don't happen.

**Comment by SUPERCILEX** [comment]
Realistically, I'm going to shut this extension down before this gets implemented. I'm working on a replacement (https://github.com/SUPERCILEX/clipboard-history/issues/3) and have landed on a design that is cross desktop environment (gnome, kde, cosmic, whatever), cross window protocol (X11, Wayland), cross client (gnome extension, native GUI, TUI, etc), and extensible so people can implement their own whatevers on top the database if they don't like the defaults. Basically it's the end all be all of clipboard managers for Linux. Now I just need to find the time to continue working on it. 😅

**Comment by SUPERCILEX** [comment]
Ringboard is available now BTW: https://github.com/SUPERCILEX/clipboard-history
