### ISSUE TITLE
Cannot open clipboard panel

### ISSUE THREAD

**Issue by rishabhs1711** [SUPERCILEX/gnome-clipboard-history#153]
I followed the instructions in the README and installed and enabled the clipboard gnome extension successfully. But the shortcut Super+shift+V doesn't seem to open the clipboard panel. So basically I cannot use the extension. I tried looking through the files to see if I can change/look at the keybindings to try and fix it, but I cannot find where the keybindings are stored.

I ran the following commands to get debugging info and have pasted the output below:

$ gnome-shell --version

** (process:51121): WARNING **: 16:58:02.002: Failed to set RT scheduler: Operation not permitted
GNOME Shell 42.5
$ echo - "GCH"
- GCH
$ gnome-extensions show clipboard-history@alexsaveau.dev | grep Version
  Version: 34
$ gsettings --schemadir ~/.local/share/gnome-shell/extensions/clipboard-histro^[^[[D^[[A^C
$ ^[[A^[[A^C
$ gsettings --schemadir ~/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/schemas list-recursively org.gnome.shell.extensions.clipboard-history
org.gnome.shell.extensions.clipboard-history cache-only-favorites false
org.gnome.shell.extensions.clipboard-history cache-size 100
org.gnome.shell.extensions.clipboard-history clear-history @as []
org.gnome.shell.extensions.clipboard-history confirm-clear true
org.gnome.shell.extensions.clipboard-history disable-down-arrow true
org.gnome.shell.extensions.clipboard-history display-mode 0
org.gnome.shell.extensions.clipboard-history enable-keybindings true
org.gnome.shell.extensions.clipboard-history history-size 1000
org.gnome.shell.extensions.clipboard-history move-item-first true
org.gnome.shell.extensions.clipboard-history next-entry @as []
org.gnome.shell.extensions.clipboard-history notify-on-copy false
org.gnome.shell.extensions.clipboard-history paste-on-selection true
org.gnome.shell.extensions.clipboard-history prev-entry @as []
org.gnome.shell.extensions.clipboard-history private-mode false
org.gnome.shell.extensions.clipboard-history process-primary-selection false
org.gnome.shell.extensions.clipboard-history strip-text false
org.gnome.shell.extensions.clipboard-history toggle-menu ['<Super><Shift>V']
org.gnome.shell.extensions.clipboard-history toggle-private-mode ['<Super><Shift>P']
org.gnome.shell.extensions.clipboard-history topbar-preview-size 10
org.gnome.shell.extensions.clipboard-history window-width-percentage 33
 
$ journalctl -n 1000000 | grep -B 10 -A 10 'clipboard-history'
Dec 08 00:32:49 pop-os PackageKit[1092]: get-updates transaction /438_ceadbeed from uid 1000 finished with success after 529ms
Dec 08 00:33:09 pop-os io.elementary.a[3125]: Child name 'updates' not found in GtkStack
Dec 08 00:33:10 pop-os PackageKit[1092]: get-packages transaction /439_aadbdbbb from uid 1000 finished with success after 633ms
Dec 08 00:33:11 pop-os PackageKit[1092]: get-updates transaction /440_ecbaddda from uid 1000 finished with success after 880ms
Dec 08 00:34:09 pop-os wpa_supplicant[673]: wlp0s20f3: CTRL-EVENT-SIGNAL-CHANGE above=0 signal=-62 noise=9999 txrate=26000
Dec 08 00:34:34 pop-os wpa_supplicant[673]: wlp0s20f3: CTRL-EVENT-SIGNAL-CHANGE above=1 signal=-60 noise=9999 txrate=26000
Dec 08 00:34:35 pop-os rtkit-daemon[911]: Supervising 7 threads of 4 processes of 1 users.
Dec 08 00:34:35 pop-os rtkit-daemon[911]: Supervising 7 threads of 4 processes of 1 users.
Dec 08 00:34:42 pop-os rtkit-daemon[911]: Supervising 7 threads of 4 processes of 1 users.
Dec 08 00:34:42 pop-os rtkit-daemon[911]: Supervising 7 threads of 4 processes of 1 users.
Dec 08 00:35:31 pop-os sudo[22621]: rishabhs1711 : TTY=pts/0 ; PWD=/home/rishabhs1711/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev ; USER=root ; COMMAND=/usr/bin/apt install gettext
Dec 08 00:35:31 pop-os sudo[22621]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
Dec 08 00:35:40 pop-os sudo[22621]: pam_unix(sudo:session): session closed for user root
Dec 08 00:35:42 pop-os PackageKit[1092]: uid 1000 is trying to obtain org.freedesktop.packagekit.system-sources-refresh auth (only_trusted:0)
Dec 08 00:35:42 pop-os PackageKit[1092]: uid 1000 obtained auth for org.freedesktop.packagekit.system-sources-refresh
Dec 08 00:35:48 pop-os NetworkManager[631]: <info>  [1701975948.3674] dhcp4 (wlp0s20f3): state changed new lease, address=172.17.50.42
Dec 08 00:35:53 pop-os rtkit-daemon[911]: Supervising 7 threads of 4 processes of 1 users.
Dec 08 00:35:53 pop-os rtkit-daemon[911]: Supervising 7 threads of 4 processes of 1 users.
Dec 08 00:35:53 pop-os rtkit-daemon[911]: Supervising 7 threads of 4 processes of 1 users.
Dec 08 00:35:53 pop-os rtkit-daemon[911]: Supervising 7 threads of 4 processes of 1 users.
Dec 08 00:36:07 pop-os rtkit-daemon[911]: Supervising 7 threads of 4 processes of 1 users.

Can anyone help?

**Comment by SUPERCILEX** [comment]
The icon will appear in your toolbar. Click that and then go to settings.

**Comment by rishabhs1711** [comment]
I do not think the icon is being displayed in the toolbar. However I tried opening the preferences through the terminal with the command:
gnome-extensions prefs clipboard-history@alexsaveau.dev

It opened a window with the following error message: 
The settings of extension clipboard-history@alexsaveau.dev had an error:
```
SyntaxError: import declarations may only appear at top level of a module
```

Stack trace:
```
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:23:33
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by SUPERCILEX** [comment]
Oh, did you install from source? Master doesn't support gnome 42 you to look at the pre-45 branch.

**Comment by rishabhs1711** [comment]
Okay so I removed this version and installed the correct version from the gnome extensions website and it works like a charm now. Thanks a lot for the help!
