### ISSUE TITLE
Desktop logs out by itself

### ISSUE THREAD

**Issue by medicamin** [SUPERCILEX/gnome-clipboard-history#155]
### Describe the bug

when gnome-clipboard-history is enabled, wait until the screen dims and goes to the lockscreen. suddenly just before the monitor turns off, desktop logs out by itself instead of just showing the lock screen.
It makes me loose all my unsaved jobs.
But with gnome-clipboard-indicator there is no such issue.
There is no conflict with other active extensions, ad I tested one by one to find the missbehaving one.

#### Versions

gnome 45.2 on wayland
extension 1.4.4 installed by source.
OS: Manjaro 23.1.1

GNOME Shell 45.2
GCH   Version: 34
org.gnome.shell.extensions.clipboard-history cache-only-favorites false
org.gnome.shell.extensions.clipboard-history cache-size 100
org.gnome.shell.extensions.clipboard-history clear-history @as []
org.gnome.shell.extensions.clipboard-history confirm-clear true
org.gnome.shell.extensions.clipboard-history disable-down-arrow true
org.gnome.shell.extensions.clipboard-history display-mode 0
org.gnome.shell.extensions.clipboard-history enable-keybindings true
org.gnome.shell.extensions.clipboard-history history-size 1000
org.gnome.shell.extensions.clipboard-history move-item-first true
org.gnome.shell.extensions.clipboard-history next-entry ['<Shift>F12']
org.gnome.shell.extensions.clipboard-history notify-on-copy false
org.gnome.shell.extensions.clipboard-history paste-on-selection true
org.gnome.shell.extensions.clipboard-history prev-entry ['<Shift>F11']
org.gnome.shell.extensions.clipboard-history private-mode false
org.gnome.shell.extensions.clipboard-history process-primary-selection false
org.gnome.shell.extensions.clipboard-history strip-text false
org.gnome.shell.extensions.clipboard-history toggle-menu ['<Shift>F10']
org.gnome.shell.extensions.clipboard-history toggle-private-mode ['<Super><Shift>P']
org.gnome.shell.extensions.clipboard-history topbar-preview-size 10
org.gnome.shell.extensions.clipboard-history window-width-percentage 20

#### Steps to repro

Just enable the extension and wait until the screen dims.

**Comment by SUPERCILEX** [comment]
Dang, that's not good. Unfortunately I don't use gnome 45 so I haven't vetted that code. Can you share logs: `$ journalctl -n 1000000 | grep -B 10 -A 10 'clipboard-history'`. Maybe that will give us a hint.
