### ISSUE TITLE
Suddenly content dissapear from the clipboard

### ISSUE THREAD

**Issue by pakosaan** [SUPERCILEX/gnome-clipboard-history#156]
### Describe the bug
Content Dissapeared from the hostory and had to turn off and on the extension to working again

#### Versions
v1.4.4

GNOME Shell 45.3
GCH   Version: 34
org.gnome.shell.extensions.clipboard-history cache-only-favorites false
org.gnome.shell.extensions.clipboard-history cache-size 100
org.gnome.shell.extensions.clipboard-history clear-history @as []
org.gnome.shell.extensions.clipboard-history confirm-clear true
org.gnome.shell.extensions.clipboard-history disable-down-arrow true
org.gnome.shell.extensions.clipboard-history display-mode 3
org.gnome.shell.extensions.clipboard-history enable-keybindings true
org.gnome.shell.extensions.clipboard-history history-size 10000
org.gnome.shell.extensions.clipboard-history move-item-first true
org.gnome.shell.extensions.clipboard-history next-entry @as []
org.gnome.shell.extensions.clipboard-history notify-on-copy false
org.gnome.shell.extensions.clipboard-history paste-on-selection false
org.gnome.shell.extensions.clipboard-history prev-entry @as []
org.gnome.shell.extensions.clipboard-history private-mode false
org.gnome.shell.extensions.clipboard-history process-primary-selection false
org.gnome.shell.extensions.clipboard-history strip-text true
org.gnome.shell.extensions.clipboard-history toggle-menu ['<Super>v']
org.gnome.shell.extensions.clipboard-history toggle-private-mode ['<Super><Shift>P']
org.gnome.shell.extensions.clipboard-history topbar-preview-size 60

**Comment by SUPERCILEX** [comment]
Maybe you cleared your `~/.cache` directory? That's where the clipboard data is stored (which is probably a mistake honestly, it should be in `/.local/share`).

**Comment by d-k-bo** [comment]
> it should be in `/.local/share`

I think `$XDG_STATE_HOME` would be even more appropriate.

The [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables) says:

>  `$XDG_STATE_HOME` defines the base directory relative to which user-specific state files should be stored. If `$XDG_STATE_HOME` is either not set or empty, a default equal to ` $HOME/.local/state` should be used.
> 
> The `$XDG_STATE_HOME` contains state data that should persist between (application) restarts, but that is not important or portable enough to the user that it should be stored in `$XDG_DATA_HOME`. It may contain:
> 
> - actions history (logs, history, recently used files, …)
> - current state of the application that can be reused on a restart (view, layout, open files, undo history, …)

**Comment by SUPERCILEX** [comment]
Yeah, though I think there's some argument to be made that clipboard data shouldn't be deleted unless the user specifically requests that. A bit like terminal history: it'd be weird if that data just suddenly disappeared.
