### ISSUE TITLE
cant disable any keyboard shortcut 

### ISSUE THREAD

**Issue by sarowarhosen03** [SUPERCILEX/gnome-clipboard-history#164]
### Describe the bug

i'm trying to edit my keyboard shortcut , but when i'm trying to disable them i cant do that 

### How To Reproduce
give users ability to disable kyboard shortcut with good ux 
#### Versions
40

GNOME Shell 45.2
GCH   Version: 40
org.gnome.shell.extensions.clipboard-history cache-only-favorites false
org.gnome.shell.extensions.clipboard-history cache-size 1024
org.gnome.shell.extensions.clipboard-history clear-history @as []
org.gnome.shell.extensions.clipboard-history confirm-clear true
org.gnome.shell.extensions.clipboard-history disable-down-arrow true
org.gnome.shell.extensions.clipboard-history display-mode 0
org.gnome.shell.extensions.clipboard-history enable-keybindings true
org.gnome.shell.extensions.clipboard-history history-size 5000
org.gnome.shell.extensions.clipboard-history move-item-first true
org.gnome.shell.extensions.clipboard-history next-entry ['F10']
org.gnome.shell.extensions.clipboard-history notify-on-copy false
org.gnome.shell.extensions.clipboard-history paste-on-selection true
org.gnome.shell.extensions.clipboard-history prev-entry ['F8']
org.gnome.shell.extensions.clipboard-history private-mode false
org.gnome.shell.extensions.clipboard-history process-primary-selection false
org.gnome.shell.extensions.clipboard-history strip-text false
org.gnome.shell.extensions.clipboard-history toggle-menu ['F9']
org.gnome.shell.extensions.clipboard-history toggle-private-mode ['F3']
org.gnome.shell.extensions.clipboard-history topbar-preview-size 1
org.gnome.shell.extensions.clipboard-history window-width-percentage 50

#### Steps to repro

What causes the crash/bug?

### Additional context (if a crash, provide stack trace)

[Screencast from 2024-03-26 23-15-53.webm](https://github.com/SUPERCILEX/gnome-clipboard-history/assets/98280301/dc0dd230-0548-4480-8c99-a323ebd48fc9)

**Comment by SUPERCILEX** [comment]
You should be able to delete the shortcut by hitting backspace while editing it.

**Comment by sarowarhosen03** [comment]
> You should be able to delete the shortcut by hitting backspace while editing it.

ow thanks go it , thanks you so much
