### ISSUE TITLE
Feature Request: Paste on Select in Clipboard Indicator

### ISSUE THREAD

**Issue by arvindchauhan1** [SUPERCILEX/gnome-clipboard-history#171]
**Automated Paste Action**: Implement a feature where selecting content in the clipboard indicator automatically triggers a paste action into the active application or text field.

**Customizable Settings**: Provide users with the ability to customize this behavior according to their preferences. Options could include enabling/disabling the automatic paste action and adjusting the delay before pasting.

**Comment by SUPERCILEX** [comment]
Wrong repo? This is already a thing.

**Comment by arvindchauhan1** [comment]
Thanks for pointing that out, I apologize for confusion
