### ISSUE TITLE
[Question] differences with the extension: Tudmotu/gnome-shell-extension-clipboard-indicator

### ISSUE THREAD

**Issue by lamyergeier** [SUPERCILEX/gnome-clipboard-history#172]
Can you please if there are some differences with the extension: Tudmotu/gnome-shell-extension-clipboard-indicator

Website: [Clipboard Indicator](https://extensions.gnome.org/extension/779/clipboard-indicator/) 
Source: [Tudmotu/gnome-shell-extension-clipboard-indicator: Clipboard manager for GNOME](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator)

**Comment by SUPERCILEX** [comment]
This extension was originally forked from Tudmotu: https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/pull/338. As for present day differences, I'm not sure.

It's also worth noting that I'm working on a new clipboard manager (that's not finished even though the README pretends like it is): https://github.com/SUPERCILEX/clipboard-history
