### ISSUE TITLE
Extension doesn't cooperate with a password manager

### ISSUE THREAD

**Issue by 3hr80FEZwlir** [SUPERCILEX/gnome-clipboard-history#175]
### Describe the bug

Entries copied from a password manager stay there permanently even though they should be purged from history by the password manager.

### How To Reproduce

1. Try out KeePassXC or Secrets password managers. 
2. Make sure that the feature of clearing copied clipboard entry is on.
3. Copy some field. 
4. See that copied content stays in Clipboard History extension permanently.

#### Versions

GNOME Shell 46.2
GCH   Version: 42
org.gnome.shell.extensions.clipboard-history cache-only-favorites false
org.gnome.shell.extensions.clipboard-history cache-size 1000
org.gnome.shell.extensions.clipboard-history clear-history @as []
org.gnome.shell.extensions.clipboard-history confirm-clear true
org.gnome.shell.extensions.clipboard-history disable-down-arrow true
org.gnome.shell.extensions.clipboard-history display-mode 0
org.gnome.shell.extensions.clipboard-history enable-keybindings true
org.gnome.shell.extensions.clipboard-history history-size 10000
org.gnome.shell.extensions.clipboard-history move-item-first true
org.gnome.shell.extensions.clipboard-history next-entry @as []
org.gnome.shell.extensions.clipboard-history notify-on-copy false
org.gnome.shell.extensions.clipboard-history paste-on-selection false
org.gnome.shell.extensions.clipboard-history prev-entry @as []
org.gnome.shell.extensions.clipboard-history private-mode false
org.gnome.shell.extensions.clipboard-history process-primary-selection false
org.gnome.shell.extensions.clipboard-history strip-text true
org.gnome.shell.extensions.clipboard-history toggle-menu ['<Shift><Control>v']
org.gnome.shell.extensions.clipboard-history toggle-private-mode @as []
org.gnome.shell.extensions.clipboard-history topbar-preview-size 10
org.gnome.shell.extensions.clipboard-history window-width-percentage 33

### Additional context (if a crash, provide stack trace)

Both apps can clear "their" clipboard entry if the extension isn't used.

**Comment by SUPERCILEX** [comment]
You need to turn on private mode while copying passwords so that the extension stops listening for clipboard changes.

**Comment by SUPERCILEX** [comment]
> I wish your words would suggest a temporary workaround

I literally just did.

**Comment by SUPERCILEX** [comment]
I doubt this will be fixed. I don't know what KeePass is doing, but I'm guessing they're setting the clipboard to an empty value? We could interpret that as "delete the last entry" but I'm pretty sure it happens in non password cases too so deleting random entries would be bad.

I'd accept a PR to be compatible with KeePass whatever that means as long as it doesn't break other functionality. But I'm personally not going to look into this.

**Comment by SUPERCILEX** [comment]
Since you're using KeePass, you might be interested in https://github.com/SUPERCILEX/gnome-clipboard-history/pull/170
