### ISSUE TITLE
Corrupted clipboard data

### ISSUE THREAD

**Issue by mlncn** [SUPERCILEX/gnome-clipboard-history#177]
### Describe the bug

Received the "Your clipboard data has been corrupted and was moved to:" message with a request to file a bug for it.

### How To Reproduce

Try copying from Hedgedoc, i guess.

#### Versions

```
GNOME Shell 44.9
GCH   Version: 41
org.gnome.shell.extensions.clipboard-history cache-only-favorites false
org.gnome.shell.extensions.clipboard-history cache-size 480
org.gnome.shell.extensions.clipboard-history clear-history @as []
org.gnome.shell.extensions.clipboard-history confirm-clear true
org.gnome.shell.extensions.clipboard-history disable-down-arrow true
org.gnome.shell.extensions.clipboard-history display-mode 2
org.gnome.shell.extensions.clipboard-history enable-keybindings true
org.gnome.shell.extensions.clipboard-history history-size 1800
org.gnome.shell.extensions.clipboard-history move-item-first true
org.gnome.shell.extensions.clipboard-history next-entry @as []
org.gnome.shell.extensions.clipboard-history notify-on-copy false
org.gnome.shell.extensions.clipboard-history paste-on-selection false
org.gnome.shell.extensions.clipboard-history prev-entry @as []
org.gnome.shell.extensions.clipboard-history private-mode false
org.gnome.shell.extensions.clipboard-history process-primary-selection false
org.gnome.shell.extensions.clipboard-history strip-text false
org.gnome.shell.extensions.clipboard-history toggle-menu ['<Super><Shift>V']
org.gnome.shell.extensions.clipboard-history toggle-private-mode ['<Shift><Control><Alt>p']
org.gnome.shell.extensions.clipboard-history topbar-preview-size 20
org.gnome.shell.extensions.clipboard-history window-width-percentage 33
```

#### Steps to repro

The text that triggered it is here, although it has already turned `í` into `Ã­ ` and `ç` into `Ã§`:

[corrupted.enc.txt](https://github.com/user-attachments/files/16089196/corrupted.enc.txt)

Hmm actually copying what appears as the `Ã ` from the corrupted log wiped the history with the same message again, probably that blank space (get it in the log) is not a normal space and is an easy way to reproduce.

### Additional context (if a crash, provide stack trace)

Above is the encrypted `corrupted.log` that was produced.

Not sure if it is relevant but wanted to emphasize that the special characters in the log are corruptions (noted above) of the special characters i was trying to paste.

**Comment by mlncn** [comment]
Clipboard data is constantly being cleared with this message now :disappointed:

**Comment by SUPERCILEX** [comment]
I don't have access to my computer until next week, but this is definitely unfortunate. I'll look into it as soon as I can.

**Comment by SUPERCILEX** [comment]
Hmmm, I can't reproduce this. I'm able to copy all of those weird characters just fine. If you're able to consistently reproduce this, can you run `sudo journalctl -f /usr/bin/gnome-shell` then trigger the bug and share whatever stack trace shows up? A corruption is supposed to log the error that cause the crash.

**Comment by mlncn** [comment]
It happened a dozen times that day … and now has not happened since.  It is working great!

I really have no idea.

**Comment by SUPERCILEX** [comment]
Huh, honestly your computer might have spazed lol. Send me lots if it happens again.
