### ISSUE TITLE
Streamline "Search and Paste": Eliminate Unnecessary Keystroke

### ISSUE THREAD

**Issue by chasoft** [SUPERCILEX/gnome-clipboard-history#184]
### Problem description

I would like to suggest an enhancement to the "Search and Paste" feature.

Currently, the process for finding and pasting an item involves:

1. Pressing the shortcut key (Shift + Win + V) to open the dialog.
2. Entering search text.
3. Pressing the Down arrow to select an item.
4. Pressing Enter to paste.

I propose simplifying this by eliminating step 3. If the user presses Enter immediately after entering the search text, the top-most matching item should be automatically pasted.

### Potential solutions/workarounds

N/A

### Additional context

N/A

**Comment by SUPERCILEX** [comment]
That's what the Ctrl+N shortcuts are for. Hit Ctrl and you should se numbers by the items to select. Does this fit the use case? I guess I could add enter, but I feel like that might be confusing.
