### ISSUE TITLE
Ubuntu + Gnome + Wayland -- Clipboard just not adding to list.

### ISSUE THREAD

**Issue by Gamedirection** [SUPERCILEX/gnome-clipboard-history#192]
### Describe the bug

The clipboard is not getting updated in the menu, nothing seems to be saved.

### How To Reproduce

When ever I install this extension via extension-manager on this particular device.

#### Versions

```
GNOME Shell 46.0
GCH   Version: 45
org.gnome.shell.extensions.clipboard-history cache-only-favorites false
org.gnome.shell.extensions.clipboard-history cache-size 100
org.gnome.shell.extensions.clipboard-history clear-history @as []
org.gnome.shell.extensions.clipboard-history confirm-clear true
org.gnome.shell.extensions.clipboard-history disable-down-arrow true
org.gnome.shell.extensions.clipboard-history display-mode 0
org.gnome.shell.extensions.clipboard-history enable-keybindings true
org.gnome.shell.extensions.clipboard-history history-size 1000
org.gnome.shell.extensions.clipboard-history ignore-password-mimes true
org.gnome.shell.extensions.clipboard-history move-item-first true
org.gnome.shell.extensions.clipboard-history next-entry @as []
org.gnome.shell.extensions.clipboard-history notify-on-copy false
org.gnome.shell.extensions.clipboard-history paste-on-selection true
org.gnome.shell.extensions.clipboard-history prev-entry @as []
org.gnome.shell.extensions.clipboard-history private-mode false
org.gnome.shell.extensions.clipboard-history process-primary-selection false
org.gnome.shell.extensions.clipboard-history strip-text false
org.gnome.shell.extensions.clipboard-history toggle-menu ['<Super>v']
org.gnome.shell.extensions.clipboard-history toggle-private-mode ['<Super><Shift>P']
org.gnome.shell.extensions.clipboard-history topbar-preview-size 10
org.gnome.shell.extensions.clipboard-history window-width-percentage 33
```

#### Steps to repro

It used to work, and now it doesnt. Unsure of how to recreate it or even debug

### Additional context (if a crash, provide stack trace)

Not really sure 

attached is an image of what I am getting.
![image](https://github.com/user-attachments/assets/ab507a42-ebc6-412f-83fb-e5c3c307c321)
![image](https://github.com/user-attachments/assets/db43770a-4008-47c2-933e-dcfc8b372889)

**Comment by Gamedirection** [comment]
[User DEVICENAME journalctl.txt](https://github.com/user-attachments/files/18210710/User.DEVICENAME.journalctl.txt)
Attached is the full journalctl log

**Comment by SUPERCILEX** [comment]
`Error writing to file: No space left on device` you're out of disk space.

**Comment by Gamedirection** [comment]
```
/dev/nvme0n1p1     663G  512G  118G  82% /
/dev/nvme0n1p2     1.1G   87M  987M   9% /boot/efi
```

it's not that full?

**Comment by SUPERCILEX** [comment]
Huh, well you probably ran out of disk space a while ago and things got corrupted. Try running `mv ~/.cache/clipboard-history@alexsaveau.dev/database.log ~/.cache/clipboard-history@alexsaveau.dev/database.log.bak` to reset the database. Log out and log back in and you should be good.

**Comment by Gamedirection** [comment]
> Huh, well you probably ran out of disk space a while ago and things got corrupted. Try running `mv ~/.cache/clipboard-history@alexsaveau.dev/database.log ~/.cache/clipboard-history@alexsaveau.dev/database.log.bak` to reset the database. Log out and log back in and you should be good.

THAT WORKED! Thanks! 100%

**Comment by SUPERCILEX** [comment]
Glad to hear it and thank you! Happy holidays :)
