### ISSUE TITLE
Can't open settings

### ISSUE THREAD

**Issue by mark-wiemer** [SUPERCILEX/gnome-clipboard-history#193]
### Describe the bug

1. Open the clipboard history via the button in the top right
2. Click settings

Expected: Settings open

Actual: Clipboard history closes without error message

#### Versions

```
GNOME Shell 47.2
GCH Extension “clipboard-history@alexsaveau.dev” doesn't exist
Could not load schemas from /home/markw/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/schemas: Failed to open file “/home/markw/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/schemas/gschemas.compiled”: open() failed: No such file or directory
```

#### Steps to repro

What causes the crash/bug?

### Additional context (if a crash, provide stack trace)

Installed on NixOS with GNOME 47 via

```nix
environment.systemPackages = with pkgs; [
  gnomeExtensions.clipboard-history
];
```

**Comment by SUPERCILEX** [comment]
I don't manage any nix packages for this extension, so you'll want to open an issue with whoever packaged it. Sorry.

**Comment by mark-wiemer** [comment]
Thanks, I've opened https://github.com/NixOS/nixpkgs/issues/368998

Note that installing from https://extensions.gnome.org/extension/4839/clipboard-history/ is working for me :)
