### ISSUE TITLE
Appear on main display in multi-monitor setup

### ISSUE THREAD

**Issue by jacksongoode** [SUPERCILEX/gnome-clipboard-history#21]
### Problem description
Currently if the top bar is hidden the main UI modal will appear on the leftmost display when using multiple monitors. It would be great if there was an option for the modal to be restricted to the user's main display.

I am currently using the [Hide Top Bar](https://github.com/mlutfy/hidetopbar) extension.

**Comment by SUPERCILEX** [comment]
Eyyyyyy, I use Hide Top Bar too! :grin: Honestly, I doubt there's anything I can do on my end since it works fine when the top bar is visible. I'm going to close in favor of #22 which would fix the issue.
