### ISSUE TITLE
Show entries when using keyboard

### ISSUE THREAD

**Issue by sojusnik** [SUPERCILEX/gnome-clipboard-history#23]
### Problem description
When selecting next or previous entry with keyboard, then a popup should be shown, like in [Tudmotu's](https://extensions.gnome.org/extension/779/clipboard-indicator/) version.

**Comment by SUPERCILEX** [comment]
Ah right, I think I didn't add this back: https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/blob/691cf1c09dc3c7e05d4ed99e03435d25efb9f278/extension.js#L849

**Comment by sojusnik** [comment]
Thanks!

Can you also replace `Copied:` in the popup with the position of the entry, that was selected via keyboard, like `2/14:`, or maybe make showing the position optional?

I think that `Copied:` is in any case redundant and is disturbing when the selected entry is shown.

**Comment by SUPERCILEX** [comment]
No, as that would require compromising on performance. The data is stored in a linked list, so the only way to get indexes would be either storing a virtual index (which would be a pain to do correctly), or iterating until we find the current item. Furthermore, I don't think it's particularly valuable to know how far along the list you are: all you need to know is what was just copied, hence the "Copied: " but.

**Comment by sojusnik** [comment]
Ok, but why not remove `Copied:` then altogether? Isn't it clear anyway, when using the keyboard, that you're copying a selection?

**Comment by SUPERCILEX** [comment]
Because you might know why a notification just popped up, but a new user might not. Here's a compromise: I moved the copied thing to the notification title so you get the full width for the copied text.

**Comment by sojusnik** [comment]
Perfect! Thanks!
