### ISSUE TITLE
Crash on start: TypeError: text is null

### ISSUE THREAD

**Issue by jacksongoode** [SUPERCILEX/gnome-clipboard-history#25]
### Describe the bug

Crashes on initialization (toggling on the extension)

#### Versions

GNOME Shell 41.4
GCH Version: 4

#### Steps to repro

Initialization.

### Additional context (if a crash, provide stack trace)

```
JS ERROR: TypeError: text is null
_hashText@/home/jackson/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/dataStructures.js:405:7
_hash@/home/jackson/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/dataStructures.js:223:14
_addToIndex@/home/jackson/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/dataStructures.js:184:23
append@/home/jackson/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/dataStructures.js:121:12
append@/home/jackson/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/dataStructures.js:315:24
_consumeStream/<@/home/jackson/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/store.js:140:23
```

**Comment by jacksongoode** [comment]
Yes, removing it seemed it to fix it (at the cost of my history :laughing:)

**Comment by SUPERCILEX** [comment]
Cool, I know where I goofed. :) I should have time to release an official update later today so you can restore your existing history (unless you completely nuked it :sweat_smile:).

**Comment by jacksongoode** [comment]
No worries! But actually, while the extension starts, the history, shortcuts are not functioning, so these things may be related as well.

**Comment by SUPERCILEX** [comment]
Yeah, that's expected. We don't bind shortcuts until everything is loaded because there are shortcuts that modify the history like prev/next or clear history. Created #27 to see if it's worth the effort of fixing. The real solution is just not crashing lol.
