### ISSUE TITLE
"Paste on selection" pastes the wrong item in Gnome Terminal

### ISSUE THREAD

**Issue by teohhanhui** [SUPERCILEX/gnome-clipboard-history#26]
### Describe the bug

"Paste on selection" always pastes the wrong item in Gnome Terminal, when clicking on any menu item.

#### Versions

- Gnome shell version: 41.4
- GCH version: 4

#### Steps to repro

1. Copy a few items: "A", "B", "C".
2. Open Gnome Terminal.
3. Click on the top bar icon to open the menu.
4. Click "A".
5. Click on the top bar icon to open the menu.
6. Click "B".

### Expected results

1. "A" is pasted.
2. "B" is pasted.

### Actual results

1. "C" is pasted.
2. "C" is pasted.

### Additional context (if a crash, provide stack trace)

`Ctrl+Shift+V` and right click context menu "Paste" works correctly.

**Comment by SUPERCILEX** [comment]
Ah, I know what's going on. What I'm doing is pretty hacky: there's no "paste this thing" API, so I have to create a virtual keyboard and simulate a paste. Right now, I chose Shift + Insert as the keyboard shortcut to paste, but apparently that's wrong: https://askubuntu.com/a/356032/456255. Changing it to Ctrl + Shift + V would fix it and should be universally accepted. The one downside is that a bunch of programs will interpret that as a "Paste as plain-text" request so people will have to repaste normally if they want the full text.

**Comment by teohhanhui** [comment]
> Changing it to Ctrl + Shift + V would fix it and should be universally accepted.

Just tried this. It doesn't work in so many places.

**Comment by teohhanhui** [comment]
Found your thread. Haha... Cool stuff.

https://discourse.gnome.org/t/api-to-paste-from-clipboard-for-extensions/8593

**Comment by SUPERCILEX** [comment]
Yup lol. I'm curious, where does Ctrl + Shift + V not work? For me, the middle mouse click doesn't work lol (though maybe that's just my mouse being weird, I'll have to try with the virtual keyboard).

**Comment by teohhanhui** [comment]
> I'm curious, where does Ctrl + Shift + V not work?

In my case, it's most places. Just some examples:

- Firefox (location bar; any text field either in the browser chrome or in web content)
- GNOME Files (search; location bar)

**Comment by SUPERCILEX** [comment]
Better idea, let's just set the primary clip too (Shift + Insert pulls from there). It seems to work fine in the terminal.
