### ISSUE TITLE
Fix down arrow not auto scrolling list

### ISSUE THREAD

**Issue by SUPERCILEX** [SUPERCILEX/gnome-clipboard-history#32]
See https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/248 and https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/251 from https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/pull/338#issuecomment-1031179212

**Comment by SUPERCILEX** [comment]
https://discourse.gnome.org/t/auto-scroll-in-st-scrollview-on-keyboard-down-arrow/9032

**Comment by VandrerenErik** [comment]
Seeing this finally solved would be nice.

**Comment by jacksongoode** [comment]
Just about to leave a comment addressing this!
