### ISSUE TITLE
CTRL+F keys can not be set using GUI

### ISSUE THREAD

**Issue by Wxrlds** [SUPERCILEX/gnome-clipboard-history#36]
### Describe the bug

When you try to assing a shortcut to i.e. CTRL+F10 using the GUI it will only set F10 to the shortcut.
Assigning CTRL+ any other key like "p" does let you set it to CTRL+P.
Using dconf-editor you can manually set it to CTRL+F10 and the shortcut will work without any problems.

### How To Reproduce

1. Open config of Clipboard History
2. Attempt to rebind i.e. the "clear history" shortcut to CTRL+F10
3. Will only assing F10

#### Versions

- Gnome shell version: 41.4
- GCH version: 8

**Comment by SUPERCILEX** [comment]
You sure you don't have a keyboard lock or something that's blocking FN keys?

**Comment by Wxrlds** [comment]
There is no lock.
As I said when I try it in the system settings I can do CTRL+F10 just fine so this is probably an issue for the Gnome Extension Program.
Will close this here
