### ISSUE TITLE
Please support mouse select, middle click copy and paste

### ISSUE THREAD

**Issue by horga83** [SUPERCILEX/gnome-clipboard-history#38]
Subject pretty much says it all.
Please support the Linux style select with mouse then middle click to paste operations.

**Comment by SUPERCILEX** [comment]
Do you mean everything you select should be added to the clipboard history?

**Comment by horga83** [comment]
I believe other clipboards handle the X11 style copy and paste by adding it when it's pasted.

Not 100% sure how that works, maybe it's not easy.

Thanks for the reply.

On February 26, 2022 10:19:53 a.m. PST, Alex Saveau ***@***.***> wrote:
>Do you mean everything you select should be added to the clipboard
>history?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/SUPERCILEX/gnome-clipboard-history/issues/38#issuecomment-1052413358
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by SUPERCILEX** [comment]
Gnome doesn't have an API to know when you paste something AFAIK, but I can support putting everything you select in the history. Note that this has unintended consequences: if you drag select for example, every time a new character is selected that counts as a new selection (so you'll end up with a, ab, abc, abcd, etc in your history). That could maybe be fixed by adding an N ms delay before registering the selection, but it's still hacky.

**Comment by horga83** [comment]
Right, it sounds like it's a bit tricky.  Thank you for considering it.
 It would be great if it works but I understand the challenge.
Maybe it's best just to leave it as is.  I have such muscle memory for
select and middle click it's hard to remember to do the other.
Mostly useful in command line work in a terminal.

Cheers
George

**Comment by SUPERCILEX** [comment]
I mean, if you're ok with the shortcomings I mentioned then I can implement it fairly easily.

**Comment by horga83** [comment]
Sure why not, lets try it, maybe it could be an option switch so as not
to upset everyone:-)

**Comment by SUPERCILEX** [comment]
BTW, is the primary clip supposed to be automatically pastable from Ctrl + V or just saved to the history. Right now I'm doing the latter.

**Comment by horga83** [comment]
There is Ctrl-C and Ctrl-V for cut and paste.  There is also highlight
with mouse, which automatically puts the selection in a buffer, then
middle click of the mouse pastes.  Super handy copying and pasting
commands into the terminal etc.

**Comment by SUPERCILEX** [comment]
And so when you highlight with your mouse, do you expect to be able to paste with Ctrl + V or only middle click?

**Comment by horga83** [comment]
Oh sorry, yes only middle click.

**Comment by SUPERCILEX** [comment]
Sweet, that's how I implemented it!
