### ISSUE TITLE
Set window width as item preview size

### ISSUE THREAD

**Issue by jacksongoode** [SUPERCILEX/gnome-clipboard-history#39]
### Problem description
Currently when moving between different history pages if the max length of any string in that page is less than the "Item preview size", the width of the window is reduced to fit the longest string. This is a little disorienting to have a window width shift between pages.

### Potential solutions/workarounds
I would either make the "Item preview size" to be default the width of the window under all conditions (as both min & max) or add a toggle to allow this behavior. I'm leaning towards the first as this is somewhat unusual behavior for a list with strings of varying lengths.

**Comment by SUPERCILEX** [comment]
Agreed, it's annoying. That's actually why I put the page buttons on the left (so they don't move). The current issue is that the item font isn't monospace, so there's no way to tell how long the window will be. I think a combination of using a monospace font (as long as it isn't too ugly) and setting the window width to be the preview size could work. Another solution could simply be never shrinking the window width. I think that'd be a lot less jarring than the current implementation and wouldn't require a monospace font.

**Comment by SUPERCILEX** [comment]
WDYT? 

| Normal | Monospace |
| --- | ----------- |
| ![image](https://user-images.githubusercontent.com/9490724/156980926-5b66cb96-6216-4aa3-9330-c6de3080848f.png) | ![image](https://user-images.githubusercontent.com/9490724/156980861-d6d19803-537c-4ac2-aef5-c7c649d0be0e.png) |

**Comment by jacksongoode** [comment]
The monospace font really doesn't look too bad. I would opt for this!

**Comment by SUPERCILEX** [comment]
Unfortunately can't figure out how to set the min width of the window. Setting `this.menu.actor.min_width` does nothing and `this.menu.actor.width` locks the width permanently. Punting this until that gets figured out. Oh and for future reference the font can be monospaced with `menuItem.style = "font-family: monospace"`.

**Comment by SUPERCILEX** [comment]
One idea I just had is to let users customize the window width instead of the number of characters shown. I'll try this out for a while (threw it up in the wip branch).

**Comment by SUPERCILEX** [comment]
Decided to go with that approach.
