### ISSUE TITLE
Clipboard position in notification not appearing

### ISSUE THREAD

**Issue by moses-bowman** [SUPERCILEX/gnome-clipboard-history#43]
### Describe the bug
I just switched from [/extension/779](https://extensions.gnome.org/extension/779/clipboard-indicator/) and I find the new features really helpful, though the clipboard position in the notification (e.g. `3/94`) is missing when cycling through the entries

### How To Reproduce
Cycle through the clipboard (prev / next)

#### Versions
GNOME Shell 40.5
GCH   Version: 8

org.gnome.shell.extensions.clipboard-history next-entry ['<Control>F12']
org.gnome.shell.extensions.clipboard-history disable-down-arrow true
org.gnome.shell.extensions.clipboard-history history-size 100000
org.gnome.shell.extensions.clipboard-history preview-size 100
org.gnome.shell.extensions.clipboard-history cache-size 1024
org.gnome.shell.extensions.clipboard-history confirm-clear true
org.gnome.shell.extensions.clipboard-history strip-text false
org.gnome.shell.extensions.clipboard-history display-mode 2
org.gnome.shell.extensions.clipboard-history topbar-preview-size 32
org.gnome.shell.extensions.clipboard-history clear-history @as []
org.gnome.shell.extensions.clipboard-history private-mode false
org.gnome.shell.extensions.clipboard-history cache-only-favorites false
org.gnome.shell.extensions.clipboard-history toggle-menu ['<Control>F10']
org.gnome.shell.extensions.clipboard-history paste-on-selection true
org.gnome.shell.extensions.clipboard-history notify-on-copy false
org.gnome.shell.extensions.clipboard-history move-item-first true
org.gnome.shell.extensions.clipboard-history enable-keybindings true
org.gnome.shell.extensions.clipboard-history toggle-private-mode ['<Super><Shift>P']
org.gnome.shell.extensions.clipboard-history prev-entry ['<Control>F11']

**Comment by SUPERCILEX** [comment]
That's intentional, see https://github.com/SUPERCILEX/gnome-clipboard-history/issues/23#issuecomment-1048204901.
