### ISSUE TITLE
Screen based panel width is inconvenient when using differen monitors

### ISSUE THREAD

**Issue by kleinph** [SUPERCILEX/gnome-clipboard-history#44]
### Describe the bug

When using different monitors (e.g. laptop used alone and with external monitor) the panel width changes if the monitors don't use the same resolution. Depending on resolution difference and settings this can make the panel unusable.

### How To Reproduce

1. Configure the panel width on a bigger/smaller external monitor.
2. Unplug the external monitor thus Gnome switching the main screen.
3. The panel is now to small or to wide

#### Versions

```
aveau.dev/schemas list-recursively org.gnome.shell.extensions.clipboard-history
GNOME Shell 41.4
GCH   Version: 9
org.gnome.shell.extensions.clipboard-history next-entry @as []
org.gnome.shell.extensions.clipboard-history disable-down-arrow true
org.gnome.shell.extensions.clipboard-history history-size 1000
org.gnome.shell.extensions.clipboard-history cache-size 100
org.gnome.shell.extensions.clipboard-history confirm-clear true
org.gnome.shell.extensions.clipboard-history strip-text true
org.gnome.shell.extensions.clipboard-history display-mode 0
org.gnome.shell.extensions.clipboard-history topbar-preview-size 10
org.gnome.shell.extensions.clipboard-history clear-history @as []
org.gnome.shell.extensions.clipboard-history private-mode false
org.gnome.shell.extensions.clipboard-history cache-only-favorites false
org.gnome.shell.extensions.clipboard-history process-primary-selection false
org.gnome.shell.extensions.clipboard-history paste-on-selection true
org.gnome.shell.extensions.clipboard-history notify-on-copy false
org.gnome.shell.extensions.clipboard-history toggle-menu ['<Super><Shift>V']
org.gnome.shell.extensions.clipboard-history move-item-first true
org.gnome.shell.extensions.clipboard-history window-width-percentage 20
org.gnome.shell.extensions.clipboard-history enable-keybindings true
org.gnome.shell.extensions.clipboard-history toggle-private-mode ['<Super><Shift>P']
org.gnome.shell.extensions.clipboard-history prev-entry @as []
```

#### Steps to repro

Panel with 10% width on external monitor (2560x1440
![grafik](https://user-images.githubusercontent.com/566413/158055948-d0129b71-6b06-4538-8582-7259e9aaf2b2.png)

Panel after unplugging external monitor, now in internal one (full HD)
![grafik](https://user-images.githubusercontent.com/566413/158056113-e6c69d48-0fc7-4429-a457-29f84b571ba2.png)

### Additional context

The issue seems only occur when unplugging the monitor and thus Gnome Shell auto-switching. If I change manually the main screen in Gnome settings the panel keeps somehow a sane width.

**Comment by SUPERCILEX** [comment]
If you reopen the panel, does it fix itself?

**Comment by kleinph** [comment]
No, I can open and close it and it stays the same.
Also I didn't have the panel open when unplugging the cable and auto-switching monitors.

**Comment by SUPERCILEX** [comment]
Ok, thanks. I'm probably using the wrong monitor.

**Comment by SUPERCILEX** [comment]
Turns out the API I was using returned a composite width of all the monitors stitched together (so waaaay too many pixels).

**Comment by SUPERCILEX** [comment]
Just released, should be fixed.

**Comment by kleinph** [comment]
> Turns out the API I was using returned a composite width of all the monitors stitched together (so waaaay too many pixels).

Ah this also explains why setting the primary screen didn't triggered the issue.

> Just released, should be fixed.

Works perfectly for me. Thanks for the quick fix!
