### ISSUE TITLE
"top bar" or "panel"?

### ISSUE THREAD

**Issue by Etamuk** [SUPERCILEX/gnome-clipboard-history#50]
Hello @SUPERCILEX ,

In pot file the top bar is called "top bar". That's right. Original in Gnome the panel is on top. But maybe someone uses an extension like Dash to panel and puts the bar on the buttom, then the "top bar" isn't at top anymore :-)

What do think about it to change "top bar" to "panel" or "bar" in pot file? 
Just a suggestion ;-)

**Comment by SUPERCILEX** [comment]
I think it's technically called the status area, so does calling it the "status bar" sound reasonable?
