### ISSUE TITLE
Clipboard remains blank - TypeError: undefined has no properties

### ISSUE THREAD

**Issue by seanleavy** [SUPERCILEX/gnome-clipboard-history#52]
### Describe the bug

The clipboard does not populate on Gnome 42.
I see a closed issue #48  that's similar but this error seems to be different:

```
JS ERROR: TypeError: undefined has no properties
                                                 loop/<@/home/sean/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/store.js:144:56
                                                 parseAvailableAware@/home/sean/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/store.js:189:7
                                                 loop@/home/sean/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/store.js:142:26
                                                 loop/<@/home/sean/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/store.js:137:11
```

### How To Reproduce
Install extension on Fedora 36 with latest Gnome 42 

#### Versions
Fedora 36
Gnome 42

GNOME Shell 42.0
GCH   Version: 11
org.gnome.shell.extensions.clipboard-history cache-only-favorites false
org.gnome.shell.extensions.clipboard-history cache-size 100
org.gnome.shell.extensions.clipboard-history clear-history @as []
org.gnome.shell.extensions.clipboard-history confirm-clear true
org.gnome.shell.extensions.clipboard-history disable-down-arrow true
org.gnome.shell.extensions.clipboard-history display-mode 0
org.gnome.shell.extensions.clipboard-history enable-keybindings true
org.gnome.shell.extensions.clipboard-history history-size 100
org.gnome.shell.extensions.clipboard-history move-item-first true
org.gnome.shell.extensions.clipboard-history next-entry @as []
org.gnome.shell.extensions.clipboard-history notify-on-copy false
org.gnome.shell.extensions.clipboard-history paste-on-selection false
org.gnome.shell.extensions.clipboard-history prev-entry @as []
org.gnome.shell.extensions.clipboard-history private-mode false
org.gnome.shell.extensions.clipboard-history process-primary-selection false
org.gnome.shell.extensions.clipboard-history strip-text false
org.gnome.shell.extensions.clipboard-history toggle-menu ['<Super><Shift>V']
org.gnome.shell.extensions.clipboard-history toggle-private-mode ['<Super><Shift>P']
org.gnome.shell.extensions.clipboard-history topbar-preview-size 10
org.gnome.shell.extensions.clipboard-history window-width-percentage 33

#### Here's zipped database.enc
[database.zip](https://github.com/SUPERCILEX/gnome-clipboard-history/files/8379791/database.zip)

**Comment by SUPERCILEX** [comment]
Can you run `ls -a ~/.cache/clipboard-history@alexsaveau.dev/` and see if there are any files besides `database.log`?

The TL;DR is that your log file is very broken and contains incorrect IDs starting with ID `50`. Is there anything important in the history you'd like to recover? The database is basically garbage so your best bet will be to run `rm ~/.cache/clipboard-history@alexsaveau.dev/database.log` and then `Alt + F2` and type `r` to restart Gnome.

**Comment by SUPERCILEX** [comment]
Also, did you change any of the extension's settings recently?

The logs make no sense: I'm seeing things like 145 or 191 adds before a delete starting at ID 51 or 50 and yet the max history size is 100. The fact that the broken IDs always start at 50 or 51 probably means something, but I have no clue. :shrug:

**Comment by seanleavy** [comment]
Hi. There were no other files there.

I rm'ed the database and its working now. Don't really care about the contents :)

I did change a few of the settings and have enabled and disabled it a few times in the past. Its also gone through a system upgrade from F35 to F36 too. Its been thoroughly abused 😄


'Tis all working grand now. Thanks!
