### ISSUE TITLE
German translation not working anymore completely

### ISSUE THREAD

**Issue by Etamuk** [SUPERCILEX/gnome-clipboard-history#54]
Hello,

I noticed the German translation seems to be not correct anymore. 
The latest version was the translation from my PR #49 wich worked for me. This file was 100% translated.

Affected are strings like:
_Window width (%)_ or
_Process primary selection_

**Comment by SUPERCILEX** [comment]
Mmmm, the other changes came from https://github.com/SUPERCILEX/gnome-clipboard-history/pull/51. I just checked with google translate and it seems like _Process primary selection_ should be _Primäre Auswahl verarbeiten_? The others look good though... can you confirm? I can make a quick update to fix that string if so.

**Comment by Etamuk** [comment]
The translations (the wording) are ok for me. Every translator has his own style. 
I think there is something wrong with the IDs, for example _#: prefs.js:134_

**Comment by SUPERCILEX** [comment]
Pretty sure those are correct... is your editor maybe not able to handle NBSPs? What specifically is broken?

**Comment by Etamuk** [comment]
I reinstalled the extension and checked it again. Three strings are not shown as translated (see scrennshots).
After that I have overwritten the translation file with the file from #49. That's working fine. 
Strange. I cannot tell you what's wrong.
I am using Poedit since years and never had problems with it. 
![Bildschirmfoto von 2022-04-06 13-26-33](https://user-images.githubusercontent.com/20098065/161967638-140c216e-e3c1-478f-aa82-1d023eeb7fa0.png)
![Bildschirmfoto von 2022-04-06 13-27-06](https://user-images.githubusercontent.com/20098065/161967641-17406e52-e2f3-46a5-8e77-2cc09a84c9f2.png)

**Comment by SUPERCILEX** [comment]
Oh dang it, I botched the release. :facepalm: I just re-uploaded the extension... it should be fixed now.

**Comment by Etamuk** [comment]
Yes, it's fixed now. Thanks!

**Comment by SUPERCILEX** [comment]
Awesome!
