### ISSUE TITLE
cannot  start the extension

### ISSUE THREAD

**Issue by takiden** [SUPERCILEX/gnome-clipboard-history#55]
### Describe the bug

this is the error from extensions tab:
```
The settings of extension clipboard-history@alexsaveau.dev had an error:

SyntaxError: identifier starts immediately after numeric literal


Stack trace:

_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

#### Versions
I am running Pop os:

OS: Pop!_OS 20.04 LTS x86_64 
Host: B550 AORUS PRO AC 
Kernel: 5.16.11-76051611-generic 
Uptime: 1 day, 7 hours, 52 mins 
Packages: 1927 (dpkg), 10 (flatpak) 
Shell: zsh 5.8 
Resolution: 1920x1080 
DE: GNOME 
WM: Mutter 
WM Theme: Pop 
Theme: Pop-dark [GTK2/3] 
Icons: Pop [GTK2/3] 
Terminal: x-terminal-emul 
CPU: AMD Ryzen 5 3600X (12) @ 3.800GHz 
GPU: NVIDIA GeForce GTX 1660 SUPER 
Memory: 3096MiB / 16005MiB 

#### output of debugging command
GNOME Shell 3.36.7
GCH   Version: 11
org.gnome.shell.extensions.clipboard-history next-entry @as []
org.gnome.shell.extensions.clipboard-history disable-down-arrow true
org.gnome.shell.extensions.clipboard-history history-size 1000
org.gnome.shell.extensions.clipboard-history cache-size 100
org.gnome.shell.extensions.clipboard-history confirm-clear true
org.gnome.shell.extensions.clipboard-history strip-text false
org.gnome.shell.extensions.clipboard-history display-mode 0
org.gnome.shell.extensions.clipboard-history topbar-preview-size 10
org.gnome.shell.extensions.clipboard-history clear-history @as []
org.gnome.shell.extensions.clipboard-history private-mode false
org.gnome.shell.extensions.clipboard-history cache-only-favorites false
org.gnome.shell.extensions.clipboard-history process-primary-selection false
org.gnome.shell.extensions.clipboard-history paste-on-selection true
org.gnome.shell.extensions.clipboard-history notify-on-copy false
org.gnome.shell.extensions.clipboard-history toggle-menu ['<Super><Shift>V']
org.gnome.shell.extensions.clipboard-history move-item-first true
org.gnome.shell.extensions.clipboard-history window-width-percentage 33
org.gnome.shell.extensions.clipboard-history enable-keybindings true
org.gnome.shell.extensions.clipboard-history toggle-private-mode ['<Super><Shift>P']
org.gnome.shell.extensions.clipboard-history prev-entry @as []

Thank you for checking this out :)

**Comment by SUPERCILEX** [comment]
Thanks for all the details! Only gnome 40 and above is supported. Though if someone else wants to add in support for older Gnome versions, I'm open to the idea.
