### ISSUE TITLE
What is "Process primary selection" ?

### ISSUE THREAD

**Issue by haoadoresorange** [SUPERCILEX/gnome-clipboard-history#56]
Sorry if this is not the right place to ask. What is the option "Process primary selection" ?

**Comment by SUPERCILEX** [comment]
Oops, I missed this. :grimacing: 

It's about the different selection types: https://wiki.archlinux.org/title/clipboard#Selections. Whenever you highlight a bit of text, that's considered a primary selection. So turning on "Process primary selection" means it'll save anything you highlight.

Please let me know if you have ideas to make that option clearer.

**Comment by haoadoresorange** [comment]
Thanks for the reply ! Yeah I figured that out after posting this (: I think a reference in the Readme would do it ?

**Comment by SUPERCILEX** [comment]
Good idea, I need to write some proper docs at some point anyway.

**Comment by paddylandau** [comment]
> Please let me know if you have ideas to make that option clearer.

Perhaps you could include a link to the help from the settings dialogue? I also had this query, but had no idea where to find documentation, so I found this thread.

Thank you 🙂

**Comment by SUPERCILEX** [comment]
That's a good idea, I created an issue to track the docs stuff: https://github.com/SUPERCILEX/gnome-clipboard-history/issues/70
