### ISSUE TITLE
Icons are not in the center of selected area

### ISSUE THREAD

**Issue by RZHSSNZDH** [SUPERCILEX/gnome-clipboard-history#57]
### The bug

I think a screenshot is better than text discribtion:
![نماگرفت از 2022-04-08 11-12-25](https://user-images.githubusercontent.com/69734726/162379911-f0ca81b7-16af-4c03-a230-071ccbcb5031.png)
The `X` symbol is not in the center of the rectangle (botton).

#### Versions

GNOME Shell 42.0
GCH org.gnome.shell.extensions.clipboard-history cache-only-favorites false
org.gnome.shell.extensions.clipboard-history cache-size 100
org.gnome.shell.extensions.clipboard-history clear-history ['Delete']
org.gnome.shell.extensions.clipboard-history confirm-clear true
org.gnome.shell.extensions.clipboard-history disable-down-arrow true
org.gnome.shell.extensions.clipboard-history display-mode 0
org.gnome.shell.extensions.clipboard-history enable-keybindings false
org.gnome.shell.extensions.clipboard-history history-size 1000
org.gnome.shell.extensions.clipboard-history move-item-first true
org.gnome.shell.extensions.clipboard-history next-entry @as []
org.gnome.shell.extensions.clipboard-history notify-on-copy false
org.gnome.shell.extensions.clipboard-history paste-on-selection true
org.gnome.shell.extensions.clipboard-history prev-entry @as []
org.gnome.shell.extensions.clipboard-history private-mode false
org.gnome.shell.extensions.clipboard-history process-primary-selection false
org.gnome.shell.extensions.clipboard-history strip-text false
org.gnome.shell.extensions.clipboard-history toggle-menu ['<Super><Shift>V']
org.gnome.shell.extensions.clipboard-history toggle-private-mode ['<Super><Shift>P']
org.gnome.shell.extensions.clipboard-history topbar-preview-size 1
org.gnome.shell.extensions.clipboard-history window-width-percentage 33

#### Steps to repro

You can see the issue when you hover mouse on a botton in the extension window.
_NOTE: My system language is an RTL language._

**Comment by SUPERCILEX** [comment]
I would consider that a gnome bug since we aren't doing anything special, but I'll leave this open if anyone wants to try and fix it.

**Comment by Digitalone1** [comment]
> I would consider that a gnome bug since we aren't doing anything special, but I'll leave this open if anyone wants to try and fix it.

Not really, a widget can be aligned horizontally to be at the center of the parent container.
