### ISSUE TITLE
Can't navigate between results with tab, up and down.

### ISSUE THREAD

**Issue by kevinhwang91** [SUPERCILEX/gnome-clipboard-history#58]
### Describe the bug

After the menu is shown, tab, up and down can't select the new result.

#### Versions

GNOME Shell 42.0
GCH   Version: 13
org.gnome.shell.extensions.clipboard-history cache-only-favorites false
org.gnome.shell.extensions.clipboard-history cache-size 100
org.gnome.shell.extensions.clipboard-history clear-history @as []
org.gnome.shell.extensions.clipboard-history confirm-clear true
org.gnome.shell.extensions.clipboard-history disable-down-arrow true
org.gnome.shell.extensions.clipboard-history display-mode 0
org.gnome.shell.extensions.clipboard-history enable-keybindings true
org.gnome.shell.extensions.clipboard-history history-size 1000
org.gnome.shell.extensions.clipboard-history move-item-first true
org.gnome.shell.extensions.clipboard-history next-entry @as []
org.gnome.shell.extensions.clipboard-history notify-on-copy false
org.gnome.shell.extensions.clipboard-history paste-on-selection true
org.gnome.shell.extensions.clipboard-history prev-entry @as []
org.gnome.shell.extensions.clipboard-history private-mode false
org.gnome.shell.extensions.clipboard-history process-primary-selection false
org.gnome.shell.extensions.clipboard-history strip-text false
org.gnome.shell.extensions.clipboard-history toggle-menu ['<Super>minus']
org.gnome.shell.extensions.clipboard-history toggle-private-mode ['<Super><Shift>P']
org.gnome.shell.extensions.clipboard-history topbar-preview-size 10
org.gnome.shell.extensions.clipboard-history window-width-percentage 33

**Comment by SUPERCILEX** [comment]
Would you mind sharing a video of what you mean? Or are you just saying that pressing down doesn't highlight the next clipboard item?

**Comment by kevinhwang91** [comment]
> Or are you just saying that pressing down doesn't highlight the next clipboard item?

Yes, like the behavior of https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator

**Comment by SUPERCILEX** [comment]
I'm going to assume this is a Gnome 42 bug since it works fine for me. Unfortunately, I'm not running 42 yet so I can't test this.

**Comment by kevinhwang91** [comment]
Yes, I am using Gnome 42.

**Comment by SUPERCILEX** [comment]
I had this bug too, but this seems to have fixed itself with some recent update. Please reopen if that's not the case for you.
