### ISSUE TITLE
Don't let `Window width` too small

### ISSUE THREAD

**Issue by hasecilu** [SUPERCILEX/gnome-clipboard-history#60]
### Describe the bug

The `Window width` is set as a % of the screen width, if is changed to a very small value (ex:5%) the window is deformed.
Maybe calculate the minimum width needed to accommodate the icons?
Of course the user can fix this making the % bigger  and that's all.

#### Versions

GNOME Shell 42.0
GCH   Version: 13
org.gnome.shell.extensions.clipboard-history cache-only-favorites false
org.gnome.shell.extensions.clipboard-history cache-size 100
org.gnome.shell.extensions.clipboard-history clear-history @as []
org.gnome.shell.extensions.clipboard-history confirm-clear true
org.gnome.shell.extensions.clipboard-history disable-down-arrow true
org.gnome.shell.extensions.clipboard-history display-mode 0
org.gnome.shell.extensions.clipboard-history enable-keybindings true
org.gnome.shell.extensions.clipboard-history history-size 1000
org.gnome.shell.extensions.clipboard-history move-item-first true
org.gnome.shell.extensions.clipboard-history next-entry @as []
org.gnome.shell.extensions.clipboard-history notify-on-copy true
org.gnome.shell.extensions.clipboard-history paste-on-selection false
org.gnome.shell.extensions.clipboard-history prev-entry @as []
org.gnome.shell.extensions.clipboard-history private-mode false
org.gnome.shell.extensions.clipboard-history process-primary-selection false
org.gnome.shell.extensions.clipboard-history strip-text false
org.gnome.shell.extensions.clipboard-history toggle-menu ['<Super><Shift>V']
org.gnome.shell.extensions.clipboard-history toggle-private-mode ['<Super><Shift>P']
org.gnome.shell.extensions.clipboard-history topbar-preview-size 10
org.gnome.shell.extensions.clipboard-history window-width-percentage 20

#### Steps to repro

Set a small `Window width`  value.

### Additional context (if a crash, provide stack trace)

![Screenshot from 2022-04-12 15-15-18](https://user-images.githubusercontent.com/53124818/163051156-41b65e2e-cc2e-4360-b258-7442b6819aad.png)

**Comment by SUPERCILEX** [comment]
I decided to not impose any limits because what if someone has an absolutely shmassive monitor? I don't want to block them from doing anything, so I let you shoot yourself in the foot. Oh well. :)
