### ISSUE TITLE
Shortcut for toggling favorite

### ISSUE THREAD

**Issue by Yajo** [SUPERCILEX/gnome-clipboard-history#61]
### Problem description

I need to toggle some favorites. Moving the hand to the mouse is slow! 😄 

### Potential solutions/workarounds

Hit <kbd>super</kbd>+<kbd>V</kbd> to open panel, navigate it with <kbd>⬆️</kbd> and <kbd>⬇️</kbd> keys, toggle favorite with <kbd>F</kbd> or other key.

### Additional context

I changed the default key to open the panel because <kbd>super</kbd>+<kbd>shift</kbd>+<kbd>V</kbd> is not very ergonomic. I hope some day gnome shell fixes https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5336 and you can ship it by default too 😃

**Comment by SUPERCILEX** [comment]
Good idea, done. I decided to explicitly NOT add a shortcut for deleting an item since we don't have an undo button and people would therefore be able to accidentally delete stuff.
