### ISSUE TITLE
Can not access extension settings

### ISSUE THREAD

**Issue by lucasjose501** [SUPERCILEX/gnome-clipboard-history#63]
### Describe the bug

Installed the extension but can't open it's settings window either by the Extensions app or the extension itself

### How To Reproduce

- Click on the extension icon in the taskbar
- Click on the "Cog" icon to open it's settings
- Window with error appears with "Something's gone wrong"

#### Versions

<pre>
OS: Zorin OS 16
Kernel: x86_64 Linux 5.13.0-39-generic

GNOME Shell 3.38.4
GCH   Version: 14
org.gnome.shell.extensions.clipboard-history next-entry @as []
org.gnome.shell.extensions.clipboard-history disable-down-arrow true
org.gnome.shell.extensions.clipboard-history history-size 1000
org.gnome.shell.extensions.clipboard-history cache-size 100
org.gnome.shell.extensions.clipboard-history confirm-clear true
org.gnome.shell.extensions.clipboard-history strip-text false
org.gnome.shell.extensions.clipboard-history display-mode 0
org.gnome.shell.extensions.clipboard-history topbar-preview-size 10
org.gnome.shell.extensions.clipboard-history clear-history @as []
org.gnome.shell.extensions.clipboard-history private-mode false
org.gnome.shell.extensions.clipboard-history cache-only-favorites false
org.gnome.shell.extensions.clipboard-history process-primary-selection false
org.gnome.shell.extensions.clipboard-history paste-on-selection true
org.gnome.shell.extensions.clipboard-history notify-on-copy false
org.gnome.shell.extensions.clipboard-history toggle-menu [&apos;&lt;Super&gt;&lt;Shift&gt;V&apos;]
org.gnome.shell.extensions.clipboard-history move-item-first true
org.gnome.shell.extensions.clipboard-history window-width-percentage 33
org.gnome.shell.extensions.clipboard-history enable-keybindings true
org.gnome.shell.extensions.clipboard-history toggle-private-mode [&apos;&lt;Super&gt;&lt;Shift&gt;P&apos;]
org.gnome.shell.extensions.clipboard-history prev-entry @as []</pre>

### Additional context (if a crash, provide stack trace)

<pre>
The settings of extension clipboard-history@alexsaveau.dev had an error:
```
Error: Could not guess unspecified GValue type
```

Stack trace:
```
addKeybinding@/home/lucas/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/prefs.js:368:9
_init@/home/lucas/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/prefs.js:92:18
buildPrefsWidget@/home/lucas/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/prefs.js:345:16
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
</pre>

### Logs:
<pre>abr 14 16:12:36 Desktop gnome-shell[2123]: Window manager warning: Trying to re-add keybinding &quot;clear-history&quot;.
abr 14 16:12:36 Desktop gnome-shell[2123]: Window manager warning: Trying to re-add keybinding &quot;prev-entry&quot;.
abr 14 16:12:36 Desktop gnome-shell[2123]: Window manager warning: Trying to re-add keybinding &quot;next-entry&quot;.
abr 14 16:12:36 Desktop gnome-shell[2123]: Window manager warning: Trying to re-add keybinding &quot;toggle-menu&quot;.
abr 14 16:12:46 Desktop gnome-shell[2123]: Window manager warning: Trying to remove non-existent keybinding &quot;clear-history&quot;.
abr 14 16:12:46 Desktop gnome-shell[2123]: Window manager warning: Trying to remove non-existent keybinding &quot;prev-entry&quot;.
abr 14 16:12:46 Desktop gnome-shell[2123]: Window manager warning: Trying to remove non-existent keybinding &quot;next-entry&quot;.
abr 14 16:12:46 Desktop gnome-shell[2123]: Window manager warning: Trying to remove non-existent keybinding &quot;toggle-menu&quot;.
</pre>

### Screenshot:
![image](https://user-images.githubusercontent.com/10009891/163462958-d88bd9d0-e107-497a-bf39-6372a4ff092e.png)

**Comment by SUPERCILEX** [comment]
Only Gnome 40 and above is supported: https://github.com/SUPERCILEX/gnome-clipboard-history/blob/master/metadata.json#L7
