### ISSUE TITLE
Deleting the last entry is automatically opening the config dialog

### ISSUE THREAD

**Issue by Digitalone1** [SUPERCILEX/gnome-clipboard-history#66]
### Describe the bug

Don't know if this happens to everybody, but at least to me anytime I click the trash icon to delete the last entry, I end up to open the config dialog because the entry disappear soon and the click event is finished on the config icon.

Don't know if this a GTK bug, anyway could something be done to prevent this behavior? 

### How To Reproduce

Just click on the last entry.

**Comment by SUPERCILEX** [comment]
Hmmm, can't repro unfortunately. Are you maybe on Gnome 40? I'm on Gnome 41 so maybe there's a bug that got fixed there.

**Comment by Digitalone1** [comment]
Gnome 42, so I think you will encounter the same issue when upgrade.

**Comment by SUPERCILEX** [comment]
Ok, thanks.

**Comment by N1vBruno** [comment]
I can't reproduce on Gnome 42 (Arch) either.

**Comment by Digitalone1** [comment]
I suppose you have a desktop PC with a mouse. It's happening to me with a touchpad on a laptop.

**Comment by neildarlow** [comment]
Seeing this on fedora Silverblue 36 Beta.

The issue isn't just restricted to the last item in the list. Deleting items within the list can trigger it. I get the impression that selecting an item for deletion causes multiple click events. In some cases the second event brings up the Settings dialog.

**Comment by SUPERCILEX** [comment]
Ok, I'm pretty sure I figured out what's going on. Widgets are reacting to both down and up events for whatever reason which means the delete happens on down and the settings click happens on up. This is really easy to reproduce with favorites: click down on the favorite icon, then while still holding the click move the mouse to some other clickable element and it will think you clicked when the mouse button is released.

**Comment by SUPERCILEX** [comment]
Ah dang it, my fault. Apparently should be using clicked instead of button pressed.

**Comment by SUPERCILEX** [comment]
Though interestingly enough, this is still an issue with the popup menu widgets which only have the `activate` signal. For example, you can click on settings and drag your mouse around to an entry to click it.

If anyone wants to file an issue with gnome, that'd be much appreciated.
