### ISSUE TITLE
Export/backup Favorites

### ISSUE THREAD

**Issue by mptpro** [SUPERCILEX/gnome-clipboard-history#69]
I would be great to be able export my save favorites to be able to restore at a later time.

Bonus: be able sen export/backup settings for the extension, as well.

thanks

**Comment by SUPERCILEX** [comment]
Already done! The entire database is contained in a single directory: `~/.cache/clipboard-history@alexsaveau.dev`. Just make copies of that and you have your backup. Overwrite the directory and that's a restore.

**Comment by SUPERCILEX** [comment]
Closing since there's no further action on my part.
