### ISSUE TITLE
Search not triggered by pressing /

### ISSUE THREAD

**Issue by dodalovic** [SUPERCILEX/gnome-clipboard-history#73]
PopOS 22.04
Nothing happens when I press `/`

Everything else is cool, thank you!

**Comment by SUPERCILEX** [comment]
Ah, yep I can repro this one. Won't have time to look into it for a bit though.

**Comment by salim-b** [comment]
Additionally, a config option to enable/disable *always focus search field when opened* would be really cool!

To always focus the search field is the default behaviour of the original [Clipboard Indicator](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator) 🙂 (although there's no config option to change that). I usually open the extension via the keyboard shortcut, then often type a partial match and select the desired clipboard entry from the subset via up/down arrow keys. Not focusing the search field initially breaks this keyboard-only workflow.

**Comment by SUPERCILEX** [comment]
@salim-b that's a gnome 42 thing. Before I upgraded it focused on the search field but that broke. :( Still not going to have time to work on this extension for another month ish unfortunately.

**Comment by salim-b** [comment]
> that's a gnome 42 thing. Before I upgraded it focused on the search field but that broke. :(

Ah, I see. Thanks for the clarification.

> Still not going to have time to work on this extension for another month ish unfortunately.

No problem, good things come to those who wait...

**Comment by dodalovic** [comment]
I noticed this was partially fixed. Whereas it always focuses now when pressing `/`, you can only type one character, if your mouse is over some entry in the clipboard list. If your mouse pointer is totally away from the list, you can type normally the full query term

**Comment by SUPERCILEX** [comment]
Yeah, that's a separate bug that's been around forever having to do with focus being given to the highlighted items instead of the search bar.

**Comment by nlpsuge** [comment]
Hi,

This might be off topic. How did you make the `searchEntry` to be focused forever even I move the cursor over the history items, the focus is not stolen from the `searchEntry`? I'm trying this feature in my extension, it just does not work like yours.

**Comment by SUPERCILEX** [comment]
No clue honestly... here's how we make it though: https://github.com/SUPERCILEX/gnome-clipboard-history/blob/a8cd5942092617fff60d38500c4638de8dc8dc42/extension.js#L109-L117

**Comment by SUPERCILEX** [comment]
Oh wait you're asking about hover, that's this line: https://github.com/SUPERCILEX/gnome-clipboard-history/blob/a8cd5942092617fff60d38500c4638de8dc8dc42/extension.js#L365

Make sure your menu items have hover=false

**Comment by nlpsuge** [comment]
> Oh wait you're asking about hover, that's this line:
> 
> https://github.com/SUPERCILEX/gnome-clipboard-history/blob/a8cd5942092617fff60d38500c4638de8dc8dc42/extension.js#L365
> 
> Make sure your menu items have hover=false

It works! 💯 Many thanks. 
This really saves me a lot of time.

**Comment by nlpsuge** [comment]
Looks `can_focus` works on the `PopupMenu.PopupSubMenuMenuItem` by:
```js
const subMenuItem = new PopupMenu.PopupSubMenuMenuItem(`a random name`, true);
subMenuItem.can_focus = false; // This line is important
```
There no `param` in the `_init` function of `PopupMenu.PopupSubMenuMenuItem` to pass `param` to its parent class `PopupBaseMenuItem`, so `{ hover: false }` doesn't works in this case. Setting  `can_focus = false` works as what I'm expecting.
