### ISSUE TITLE
2 Quick Suggestions

### ISSUE THREAD

**Issue by git-Hmmm** [SUPERCILEX/gnome-clipboard-history#75]
1. Please make it as poup instead of attaching it to top bar, you can also add option in settings to detach it from that top bar so that other users those who liked it attached with top bar don't feel sad.
2. Please decrease the search bar padding it's too high and doesn't looks good
![image](https://user-images.githubusercontent.com/102938585/167247181-b92a96ee-01c4-4ed0-a00a-3e41437c8291.png) 

Thank You for making such a great extension, btw I am copyq user but sadly it doesn't works in wayland so I shifted to this extension :-)

**Comment by git-Hmmm** [comment]
IDK but if you have problem in detaching the popup then you can do something like this
![image](https://user-images.githubusercontent.com/102938585/167247573-bae8c9e0-3522-49dc-9beb-7ef2bae7862f.png)
use tab layout like dash to panel one tab for settings and one for the clipboard :-)

**Comment by SUPERCILEX** [comment]
Gonna close this issue because the padding was tweaked in ce2f5f0bb177e14f8b5de53b9e0675686576d4bf and there's already an issue open for making it pop up: https://github.com/SUPERCILEX/gnome-clipboard-history/issues/22
