### ISSUE TITLE
Automatically Focus Topmost Clipboard Entry

### ISSUE THREAD

**Issue by maran-e** [SUPERCILEX/gnome-clipboard-history#81]
When I search for an entry, that usually ends up at the top. But, I have press arrow down to select it and then press enter.

It would be great if the topmost item is automatically in focus when we open the window as well as during search until changed
using arrow keys or mouse. This avoids the need to use arrow keys on the most common usage flow.

Since clipboard history is a frequently used feature and and arrow keys are hard to reach (no vim mode), it would be great if this gets implemented.

Thank you for the awesome project.

**Comment by SUPERCILEX** [comment]
See https://github.com/SUPERCILEX/gnome-clipboard-history/issues/73 for the focus bug. About the first item being focused while searching, that's unfortunately not possible because the text box needs to be focused.
