### ISSUE TITLE
Seeing continues error log in journal

### ISSUE THREAD

**Issue by romfreiman** [SUPERCILEX/gnome-clipboard-history#85]
Fedora 26, 

gnome-shell[1120649]: JS ERROR: Error: getSettings() can only be called from extensions
                                                            getSettings@resource:///org/gnome/shell/misc/extensionUtils.js:189:15
                                                            log_level@/home/rom/.local/share/gnome-shell/extensions/gnome-clipboard@b00f.github.io/log.js:12:35
                                                            info@/home/rom/.local/share/gnome-shell/extensions/gnome-clipboard@b00f.github.io/log.js:28:9
                                                            _updateHistory/<@/home/rom/.local/share/gnome-shell/extensions/gnome-clipboard@b00f.github.io/clipboardPanel.js:188:17

**Comment by SUPERCILEX** [comment]
Fedora 26 uses gnome 3.24 which isn't supported. Only gnome 40 and above is supported.

**Comment by romfreiman** [comment]
Ooops typo :]
Fedora 36 of course

**Comment by SUPERCILEX** [comment]
Oh wait I also noticed this is the wrong extension. You stack trace points to https://github.com/b00f/gnome-clipboard.
