### ISSUE TITLE
Add html and markdown support

### ISSUE THREAD

**Issue by headkaze** [SUPERCILEX/gnome-clipboard-history#86]
Thanks for this great extension.

I wanted to be able to convert html text in the clipboard to markdown.

I have implemented the feature on my own fork: https://github.com/headkaze/gnome-clipboard-history

Please take a look and let me know what you think. Is it something you'd be interested in merging?

**Comment by SUPERCILEX** [comment]
This looks pretty cool, but it's far too specialized to be put in a clipboard manager in my opinion. Thanks for asking though! :)

A better approach would be to create a new extension that can be activated with a click or a shortcut. On activation, it looks at what's currently in the clipboard, understands if it's html or markdown, does the conversion, and then writes the output back into the clipboard.

**Comment by headkaze** [comment]
I disagree that it's too specialized to have the ability to paste the raw markup, html or convert to markdown. It's also the first step to adding support for image formats.

![Clipboard](https://user-images.githubusercontent.com/1698401/173117350-976dd5f5-a648-47c4-98a8-0168a9fdb3f1.png)

As you can see from the screenshot it adds two icons next to any clipboard entry that contains a **text/html** mimetype.

```js
let mimetypes = Clipboard.get_mimetypes(St.ClipboardType.PRIMARY);

if (mimetypes.includes("text/plain")) {
  Clipboard.get_text(St.ClipboardType.PRIMARY, (_, text) => {
    if (mimetypes.includes("text/html")) {
      Clipboard.get_content(St.ClipboardType.PRIMARY, "text/html", (_, content) => {
        if (content && content.get_size() > 0) {
          let html = new TextDecoder().decode(content.get_data());
          this._processClipboardContent(text, html);
          this._primaryClipboardCallbackId = undefined;
          return false;
        }
        else {
          this._processClipboardContent(text);
          this._primaryClipboardCallbackId = undefined;
          return false;
        }
      });
    }
    else {
      this._processClipboardContent(text);
      this._primaryClipboardCallbackId = undefined;
      return false;
    }
  });
}
```

Currently the html is stored as text appended to the raw text.

```js
function _storeTextOp(text, html) {
  return (dataStream) => {
    dataStream.put_byte(OP_TYPE_SAVE_TEXT, null);
    dataStream.put_string(text, null);
    if (html) {
      dataStream.put_string(html, null);
    }
    dataStream.put_byte(0, null); // NUL terminator
    dataStream.put_uint32(text.length, null);
    return true;
  };
}
```

It would be quite easy to store the raw bytes as base64 and add support for **image/png**

```js
const GLib = imports.gi.GLib;
const new_data = GLib.Bytes.new(content.get_data());
// convert raw_data to base64 then store
```

The main issue I'm facing is if I restore the clipboard using `Clipboard.set_content(St.ClipboardType.PRIMARY, "text/html", ..)` it will no longer contain a **text/plain** entry. For many applications you can't paste anything that doesn't have a **text/plain** mimetype entry.

After looking at [st_clipboard_set_content](https://github.com/GNOME/gnome-shell/blob/main/src/st/st-clipboard.c#L293) it only appears to allow setting **one** mimetype. We can see this using `xclip -o -t TARGETS -selection clipoard`. It does state `@mimetype is a semi-colon separated list of mime-type strings.` but it does not allow us to pass in **text/html;text/plain**. I believe it's actually for entries such as **text/plain;charset=utf-8** but not actually for setting multiple mimetypes. We need a `st_clipboard_set_content` function that will allow us to set multiple mimetypes in one call. Then we can have the clipboard entries paste the original markup version, as well as have icons for plain text, html or markdown conversion.

At least with my fork a user can access the raw html but as demonstrated in the video in [Feature request to support markup language #118 ](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/118) anything containing markup such as links is lost when restoring through the extension.

**Comment by SUPERCILEX** [comment]
It's the conversion part that's too specialized. Again, it'd be much better
suited as a separate program that reads and writes the clipboard.

About supporting arbitrary mime types, I would love that! (Currently
offline so I can't find the issue number, but I have an issue open to do
that.) I'd want it to be properly designed though... Here's my ideal
scenario:
- Everything is stored as raw bytes with the mime type.
  - I doubt this is possible because the API sucks.
- Display values for known mime types.
- Write the raw bytes into the clipboard.

We'd have to see what's possible with the API.

About stuff not being pasteable, doesn't Ctrl Shift V work?

Honestly I'm just waiting to see what system76 does with the Cosmic DE
because all of this would be so much easier in Rust.

**Comment by headkaze** [comment]
> It's the conversion part that's too specialized. Again, it'd be much better suited as a separate program that reads and writes the clipboard.

I'd rather not have to maintain my own fork but I really need this feature.

> Currently offline so I can't find the issue number, but I have an issue open to do that

I believe you're referring to [Support arbitrary mime types (including images) #6](https://github.com/SUPERCILEX/gnome-clipboard-history/issues/6)

> Everything is stored as raw bytes with the mime type

`Gio.DataOutputStream` does not support writing raw bytes so I guess we'll need to write the data as a base64 encoded string?

> Display values for known mime types

I've seen the [feature/cache-images](https://github.com/headkaze/gnome-shell-extension-clipboard-indicator/tree/feature/cache-images) fork which displays an icon of the image. Another way would be to inspect the text/html and display the image name or *alt* text.

> Write the raw bytes into the clipboard

It's quite simple using set_content. This is how I set back the **text/html**:

```js
const content = ByteArray.toGBytes(ByteArray.fromString(entry.html));
Clipboard.set_content(St.ClipboardType.CLIPBOARD, 'text/html', content);
Clipboard.set_content(St.ClipboardType.PRIMARY, 'text/html', content);
```

> About stuff not being pasteable, doesn't Ctrl Shift V work?

There's no problem pasting anything. The problem is because we can't set multiple mimetypes we can't set **text/plain** and **text/html** at the same time. That's why you really need the extra icon to paste the clipboard with markup (not to be confused with the markdown conversion icon)

> Honestly I'm just waiting to see what system76 does with the Cosmic DE because all of this would be so much easier in Rust.

I did look into using Gtk which allows setting multiple mimetypes but unfortunately [set_with_data](https://docs.gtk.org/gtk3/method.Clipboard.set_with_data.html) isn't callable from Javascript. Another alternative is to call to shell with something like  `xclip` but I prefer the solution in my fork.

**Comment by SUPERCILEX** [comment]
Yup, it's #6.

For the output steam, we can use https://gjs-docs.gnome.org/gio20~2.66p/gio.outputstream#method-write_all. And then https://gjs-docs.gnome.org/gio20~2.66p/gio.inputstream#method-read_bytes_async for reading.

The image support in the original extension wasn't able to solve aspect ratio issues, party because it's trying to cram an image into an icon. Also my ideal UI shows the image on hover so all the items have a consistent size. I think something similar can be achieved by making image items submenus that you click to expand.

> The problem is because we can't set multiple mimetypes we can't set text/plain and text/html at the same time.

I'm saying that that shouldn't matter ideally. If you copied mine type X, then we're going to give you back mime type X. Turning that into plain text is your problem (which should just be a Shift V).

**Comment by headkaze** [comment]
> For the output steam, we can use https://gjs-docs.gnome.org/gio20~2.66p/gio.outputstream#method-write_all. And then https://gjs-docs.gnome.org/gio20~2.66p/gio.inputstream#method-read_bytes_async for reading.

Thanks for this. I'll look into this at some point.

> The image support in the original extension wasn't able to solve aspect ratio issues, party because it's trying to cram an image into an icon. Also my ideal UI shows the image on hover so all the items have a consistent size. I think something similar can be achieved by making image items submenus that you click to expand.

Perhaps we need to look into a plugin system for additional mime support?

> > The problem is because we can't set multiple mimetypes we can't set text/plain and text/html at the same time.
> 
> I'm saying that that shouldn't matter ideally. If you copied mine type X, then we're going to give you back mime type X. Turning that into plain text is your problem (which should just be a Shift V).

Unfortunately it's more complicated than that. If you copy text in Firefox for example it will store a bunch of different mime types in the clipboard.

ie.
```sh
$ xclip -o -t TARGETS
TIMESTAMP
TARGETS
MULTIPLE
text/html
text/_moz_htmlcontext
text/_moz_htmlinfo
UTF8_STRING
COMPOUND_TEXT
TEXT
STRING
text/plain;charset=utf-8
text/plain
text/x-moz-url-priv
```

Say we store `text/html` and then restore it using [set_content](https://docs.gtk.org/gdk4/method.Clipboard.set_content.html) you will find that many applications do not support it so pasting will do nothing. We need at the least `text/html` and `text/plain`.

I believe the only solution is to use a [ContentProvider](https://docs.gtk.org/gdk4/class.ContentProvider.html) and [new_for_bytes](https://docs.gtk.org/gdk4/ctor.ContentProvider.new_for_bytes.html) for each mimetype.
