### ISSUE TITLE
Hot corner extension support

### ISSUE THREAD

**Issue by pc00per** [SUPERCILEX/gnome-clipboard-history#88]
### Problem description
Whoever using [hot corner extended](https://github.com/G-dH/custom-hot-corners-extended), is there an entry for adding clipboard pop-up there?
### Potential solutions/workarounds
Currently have no idea how to work this out.
### Additional context
Does it also need support from hot-corners-extended too?
Great Extension btw. Must need as gnome-shell lacks it.

**Comment by SUPERCILEX** [comment]
Closing in favor of the other issue.
