### ISSUE TITLE
Mouse pointer position upon invocation should not affect which item to paste

### ISSUE THREAD

**Issue by gpothier** [SUPERCILEX/gnome-clipboard-history#91]
### Describe the bug

Currently, the behavior of the extension changes depending upon where the mouse pointer happens to be when invoking the popup, which hinders keyboard-only operation. If the mouse pointer happens to be at a location covered by the popup, the item under the mouse pointer is pasted when hitting enter, even when not moving the mouse at all. If the mouse pointer is not at a location covered by the popup, hitting enter pastes the most recent item, and keyboard arrow navigation also starts at the most recent item, as expected.

I think selecting an item with the mouse should be in response to mouse click, not the mouse merely being over an item. 

### How To Reproduce

Hit the invocation keyboard shortcut with the mouse at a location covered by the popup, and press enter. The item under the mouse pointer is pasted

#### Versions

GNOME Shell 42.2
GCH   Version: 16
org.gnome.shell.extensions.clipboard-history cache-only-favorites false
org.gnome.shell.extensions.clipboard-history cache-size 200
org.gnome.shell.extensions.clipboard-history clear-history @as []
org.gnome.shell.extensions.clipboard-history confirm-clear true
org.gnome.shell.extensions.clipboard-history disable-down-arrow true
org.gnome.shell.extensions.clipboard-history display-mode 0
org.gnome.shell.extensions.clipboard-history enable-keybindings true
org.gnome.shell.extensions.clipboard-history history-size 1300
org.gnome.shell.extensions.clipboard-history move-item-first true
org.gnome.shell.extensions.clipboard-history next-entry @as []
org.gnome.shell.extensions.clipboard-history notify-on-copy false
org.gnome.shell.extensions.clipboard-history paste-on-selection true
org.gnome.shell.extensions.clipboard-history prev-entry @as []
org.gnome.shell.extensions.clipboard-history private-mode false
org.gnome.shell.extensions.clipboard-history process-primary-selection false
org.gnome.shell.extensions.clipboard-history strip-text false
org.gnome.shell.extensions.clipboard-history toggle-menu ['<Primary><Alt>v']
org.gnome.shell.extensions.clipboard-history toggle-private-mode ['<Super><Shift>P']
org.gnome.shell.extensions.clipboard-history topbar-preview-size 10
org.gnome.shell.extensions.clipboard-history window-width-percentage 58

#### Steps to repro

As indicated above

**Comment by SUPERCILEX** [comment]
Hmmm, I'm really not sure what to do about this one. I've run into it myself, but that's just how gnome works AFAIK. I need to check whether or not this is an OS bug or just gnome, as in if I open a menu selector in some other GUI will having the mouse there select an item or not. If not, then I think this should be fixed on the gnome side.

**Comment by SUPERCILEX** [comment]
Actually, I think I found an option that does exactly what you want. Can you run this command, restart gnome (alt f2 then r), and then check that the issue was fixed?

```bash
cd ~/.local/share/gnome-shell/extensions/clipboard-history@alexsaveau.dev/ && curl -L https://pastebin.com/raw/UEzYiFmd | patch
```

**Comment by SUPERCILEX** [comment]
Re-open to get confirmation.

**Comment by gpothier** [comment]
Hi Alex, yes it works! Thank you so much.
Regards,
g

**Comment by SUPERCILEX** [comment]
Sweet!
