### ISSUE TITLE
Exclude caching entries from particular processes (e.g., password managers)

### ISSUE THREAD

**Issue by posita** [SUPERCILEX/gnome-clipboard-history#92]
I don't know how feasible this is, but it would be nice to be able to blacklist apps from being able to contribute to the clipboard history (e.g., [this](https://softwarerecs.stackexchange.com/questions/37957/clipboard-manager-with-ability-exclude-applications)). One common use case is that items copied from a password manager (e.g., 1Password) should probably be prevented from making it into the history. It would be nice not to have to remember to enable and disable private mode each time (which is error prone).

**Comment by SUPERCILEX** [comment]
Not likely to happen anytime soon, but good idea.

**Comment by CristianKerr** [comment]
This is very important feature I would say. Maybe easier implementation could be something like: if the extensions know, which window is active at any moment (by e.g. title), it could turn private mode automatically when excluded program window becomes active and turn private mode off after exactly one paste happens.

**Comment by SUPERCILEX** [comment]
Fixed in https://github.com/SUPERCILEX/gnome-clipboard-history/pull/170 and released for Gnome 46 as extension version 43 (once it's approved).
